### ISSUE TITLE
Minecraft 1.18.2: Bug on Menu Boss 4.3.1

### ISSUE THREAD

**Issue by louanfontenele** [kangarko/Boss#1004]
I found a bug when i try to create a new boss
```sh
[20:22:04 INFO]: [Boss] Boss 4.3.1 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file.
[20:22:04 INFO]: org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.MenuPagged.updatePage(MenuPagged.java:318)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.MenuPagged.access$200(MenuPagged.java:35)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.MenuPagged$2.onClickedInMenu(MenuPagged.java:296)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1047)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.MenuPagged.onButtonClick(MenuPagged.java:467)
[20:22:04 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
[20:22:04 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source)
[20:22:04 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[20:22:04 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:22:04 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:22:04 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[20:22:04 INFO]: [Boss] !-----------------------------------------------------!
[20:22:04 INFO]: [Boss]  Error clicking in menu CreateMenu{}
[20:22:04 INFO]: [Boss] !-----------------------------------------------------!
```

This error happens when i try to create a boss, precisely when I am choosing eggs and I go to the other page

**Comment by louanfontenele** [comment]
```sh
[20:32:50 ERROR]: Could not pass event InventoryClickEvent to Boss v4.3.1
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:589) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.Menu.animateTitle(Menu.java:687) ~[Boss.jar:?]
        at org.mineacademy.boss.menu.boss.DeathMenu$ReinforcementsMenu.canEditItem(DeathMenu.java:550) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuContainerChances.isActionAllowed(MenuContainerChances.java:220) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:88) ~[Boss.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-237]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:32:52 ERROR]: Could not pass event InventoryClickEvent to Boss v4.3.1
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:589) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.Menu.animateTitle(Menu.java:687) ~[Boss.jar:?]
        at org.mineacademy.boss.menu.boss.DeathMenu$ReinforcementsMenu.canEditItem(DeathMenu.java:550) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuContainerChances.isActionAllowed(MenuContainerChances.java:220) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:88) ~[Boss.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-237]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:32:54 ERROR]: Could not pass event InventoryClickEvent to Boss v4.3.1
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:589) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.Menu.animateTitle(Menu.java:687) ~[Boss.jar:?]
        at org.mineacademy.boss.menu.boss.DeathMenu$ReinforcementsMenu.canEditItem(DeathMenu.java:550) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuContainerChances.isActionAllowed(MenuContainerChances.java:220) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:88) ~[Boss.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-237]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:32:55 ERROR]: Could not pass event InventoryClickEvent to Boss v4.3.1
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:589) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.Menu.animateTitle(Menu.java:687) ~[Boss.jar:?]
        at org.mineacademy.boss.menu.boss.DeathMenu$ReinforcementsMenu.canEditItem(DeathMenu.java:550) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuContainerChances.isActionAllowed(MenuContainerChances.java:220) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:88) ~[Boss.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-237]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:32:56 ERROR]: Could not pass event InventoryClickEvent to Boss v4.3.1
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:589) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.Menu.animateTitle(Menu.java:687) ~[Boss.jar:?]
        at org.mineacademy.boss.menu.boss.DeathMenu$ReinforcementsMenu.canEditItem(DeathMenu.java:550) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuContainerChances.isActionAllowed(MenuContainerChances.java:220) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:88) ~[Boss.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-237]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:32:56 ERROR]: Could not pass event InventoryClickEvent to Boss v4.3.1
org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in FoodMetaData or its superclasses
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:199) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:176) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1532) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:622) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:589) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.Menu.animateTitle(Menu.java:687) ~[Boss.jar:?]
        at org.mineacademy.boss.menu.boss.DeathMenu$ReinforcementsMenu.canEditItem(DeathMenu.java:550) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuContainerChances.isActionAllowed(MenuContainerChances.java:220) ~[Boss.jar:?]
        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:88) ~[Boss.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-237]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1506) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
````

It's happening when I'm going to Death Settings>Reinforcements

**Comment by kangarko** [comment]
Thanks, will fix asap.
