### ISSUE TITLE
Minecraft 1.18 - Boss 4.3.2 - Error when delete a boss and Attributes is not working

### ISSUE THREAD

**Issue by louanfontenele** [kangarko/Boss#1007]
I'm getting this error when i try to delete a boss
```sh
[00:21:00 INFO]: [Boss] Boss 4.3.2 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[00:21:00 INFO]: org.mineacademy.boss.lib.exception.FoException: Report: Boss Herobrine.yml not loaded. Available: [Herobrine, ElderEnder]
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.lib.Valid.checkBoolean(Valid.java:90)
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.lib.settings.ConfigItems.removeItem(ConfigItems.java:229)
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.model.Boss.removeBoss(Boss.java:2209)
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.menu.boss.BossMenu.lambda$new$3(BossMenu.java:114)
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.button.ButtonRemove$RemoveConfirmButton.onClickedInMenu(ButtonRemove.java:136)
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1047)
[00:21:00 INFO]: at Boss.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
[00:21:00 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor864.execute(Unknown Source)
[00:21:00 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[00:21:00 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:21:00 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:21:00 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[00:21:00 INFO]: [Boss] !-----------------------------------------------------!
[00:21:00 INFO]: [Boss]  Error clicking in menu MenuDialogRemove{}
[00:21:00 INFO]: [Boss] !-----------------------------------------------------!
```
And attributes is not working
![image](https://user-images.githubusercontent.com/2886066/158044931-e188dcf2-c6f9-4056-a1b9-62fca5d1722e.png)

**Comment by kangarko** [comment]
Thanks, will fix
