### ISSUE TITLE
getting recurrent errors in logs / lag

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#101]
Like this:

[22:12:11] [Server thread/INFO]: [0;30;1m[21mBOSS [0;30;1m//[0;37;22m Boss 1.6.10 encountered a cOm9! Please check your error.log and report this issue with the information in that file.[m
[22:12:11] [Server thread/WARN]: [Boss] Task #7177078 for Boss v1.6.10 generated an exception
me.kangarko.boss.final. .cOm9: Report / Cannot remove 'ad8feffa-0847-4412-adab-109491377dae' as it is not in the list!
	at me.kangarko.boss.final. .com2.protected(SourceFile:30) ~[Boss-1.6.10.jar:?]
	at me.kangarko.boss.final. .B.protected(SourceFile:58) ~[Boss-1.6.10.jar:?]
	at me.kangarko.boss.final. .aE$aux.run(SourceFile:260) ~[Boss-1.6.10.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-1988d7f]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-1988d7f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-1988d7f]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-1988d7f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-1988d7f]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-1988d7f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by kangarko** [comment]
Thank you for reporting, I have fixed this.
