### ISSUE TITLE
[Boss] Task #16183287 for Boss v1.6.10 generated an exception me.kangarko.boss.final. .cOm9: Report / Cannot remove 'af81f25f-0b08-4989-a43b-395541e2184d' as it is not in the list!

### ISSUE THREAD

**Issue by valenvaio** [kangarko/Boss#102]
[13:47:54] [Server thread/INFO]: This server is running Paper version git-Paper-1391 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
....
[17:57:37 WARN]: [Boss] Task #16183287 for Boss v1.6.10 generated an exception
me.kangarko.boss.final. .cOm9: Report / Cannot remove 'af81f25f-0b08-4989-a43b-395541e2184d' as it is not in the list!
at me.kangarko.boss.final. .com2.protected(SourceFile:30) ~[Boss-1.6.10.jar:?]
at me.kangarko.boss.final. .B.protected(SourceFile:58) ~[Boss-1.6.10.jar:?]
at me.kangarko.boss.final. .aE$aux.run(SourceFile:260) ~[Boss-1.6.10.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1391]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1391]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min

**Comment by mibby** [comment]
@kangarko Can also confirm happening with v1.6.10. Spamming ```Cannot remove {UUID}``` for hundreds of different ids.
```
[00:00:02] [Server thread/INFO]: BOSS // Boss 1.6.10 encountered a cOm9! Please check your error.log and report this issue with the information in that file.
[00:00:02] [Server thread/WARN]: [Boss] Task #183528 for Boss v1.6.10 generated an exception
me.kangarko.boss.final. .cOm9: Report / Cannot remove '89be49c8-ca91-4cc6-a1bb-7f3a17222349' as it is not in the list!
	at me.kangarko.boss.final. .com2.protected(SourceFile:30) ~[Boss-1.6.10.jar:?]
	at me.kangarko.boss.final. .B.protected(SourceFile:58) ~[Boss-1.6.10.jar:?]
	at me.kangarko.boss.final. .aE$aux.run(SourceFile:260) ~[Boss-1.6.10.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1413]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1413]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by kangarko** [comment]
Thank you for reporting, I have fixed this.
