### ISSUE TITLE
1.18.2: Boss Custom Enchants get deleted on Server Restart

### ISSUE THREAD

**Issue by Miryex** [kangarko/Boss#1021]
Version: Paper version git-Paper-276 (MC: 1.18.2) 

When setting Armor / Drops to Items with Custom Enchants the Bosses lose those Items on Server restart.
But if you replace the boss files with the correct ones and reload while the server is running they work fine, 
it just deletes them on restart

Error: 
SerializedMap does not know how to convert CraftMetaEnchantedBook: ENCHANTED_META:{meta-type=ENCHANTED, stored-enchants={BOLT=1}}
FoException Report: SerializedMap does not know how to convert CraftMetaEnchantedBook: ENCHANTED_META:{meta-type=ENCHANTED, stored-enchants={BOLT=1}}
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.collection.SerializedMap.of(SerializedMap.java:1089)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.collection.SerializedMap.getMap(SerializedMap.java:657)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.SerializeUtil.deserializeItemStack(SerializeUtil.java:694)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.loadDrops(Boss.java:404)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.onLoad(Boss.java:362)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1147)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.<init>(Boss.java:316)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.<init>(Boss.java:301)
	 at jdk.internal.reflect.GeneratedConstructorAccessor145.newInstance(Unknown Source)
	 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:202)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:160)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:146)
	 at Boss-4.3.3.jar//org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:108)
	 at Boss-4.3.3.jar//org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2210)
	 at Boss-4.3.3.jar//org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
	 at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)

Ill upload the Custom Enchant Plugin if needed

**Comment by kangarko** [comment]
Thanks, please remove your Boss file or remove its drops section by opening the yml, and use the next release. Let me know below if you will still encounter issues.
