### ISSUE TITLE
1.18.2: Error when trying to press return in individual player drops menu

### ISSUE THREAD

**Issue by Korwey** [kangarko/Boss#1025]
Hello!
Here's the error.

```
------------------------------------[ 05.04.2022 20:25:06 ]-----------------------------------
Boss 4.3.4 encountered a NullPointerException
Running Purpur 1.18.2-R0.1-SNAPSHOT and Java 17.0.2
Plugins: PlaceholderAPI v2.11.1, PlugMan v2.2.2, WhitelistPlus v1.3, HolographicDisplays v3.0.0-SNAPSHOT-b205, ConsoleSpamFix v1.8.6, AntiGrief v1.0, OldCombatMechanics v1.10.0, FireFreeze v2.2, FyreTab v1.0, VoxelSniper v6.1.2, LessRandomTeleport v1.0, FyreTP v1.0, MasterCooldowns v1.3, LuckPerms v5.4.9, VoidGen v2.2.1, SaveRodOfficial v2.7.1, SirBlobmanCore v2.3.5, ClearLag v3.2.1, ChangeSlots v2.3.0, ProtocolLib v4.8.0, HamsterAPI v0.1.8, MVdWPlaceholderAPI v3.1.1, Vouchers v1.9.1, SignEdit v1.13.4, FeatherBoard v5.1.0, VoidKill v1.0, FyreStat v1.0, scriptcraft v3.4.0-2019-01-20, FyreRestart v1.0, Vault v1.7.3-b131, UnbreakableAnvils v1.3.1, ChatGames v8.1, FyreEmoji v1.0, CrazyCrates v1.10.3, FyreLevels v1.0, MoneyPouch v3.5, PlayerVaults v4.1.16, ClickLimiter v0.1.1, Essentials v2.19.3, HoloExtension v0.0.4.4 Alpha, HeadDatabase v4.12.1, Multiverse-Core v4.3.2-SNAPSHOT-b868, FastAsyncWorldEdit v2.0.2-SNAPSHOT-118;3ee9797, CrazyAuctions v1.2.17-SNAPSHOT-Build#42, EssentialsChat v2.19.3, DeluxeMenus v1.13.5-DEV-null, TAB v3.1.0, iName v1.0, ChatControlRed v10.10.1, FyreMoney v1.0, WorldGuard v7.0.4+f7ff984, UltraBar v2.3.1.1, EssentialsSpawn v2.19.3, ExecutableItems v3.3.2, TreasureChest v8.5, Citizens v2.0.29-SNAPSHOT (build 2509), Shopkeepers v2.14.0, CrazyEnvoy v1.3.10-RELEASE, Boss v4.3.4, FyreMenu v1.1, FyreShop v1.0, FyreGuild v1.0, CombatLogX v10.4.2.4, TitleManager v2.3.4, PremiumVanish v2.7.12
----------------------------------------------------------------------------------------------

More Information: 
Error clicking in menu IndividualPlayerDropMenu{}
NullPointerException Cannot invoke "org.mineacademy.boss.lib.model.Tuple.getKey()" because "tuple" is null
	 at Boss-4.3.4.jar//org.mineacademy.boss.menu.boss.DeathMenu$DropsMenu$PlayerDropsMenu$IndividualPlayerDropMenu.onMenuClose(DeathMenu.java:456)
	 at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.MenuContainerChances.onMenuClose(MenuContainerChances.java:328)
	 at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.Menu.handleClose(Menu.java:1064)
	 at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.button.ButtonReturnBack.onClickedInMenu(ButtonReturnBack.java:85)
	 at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1048)
	 at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor575.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks, looking into it

**Comment by kangarko** [comment]
Will get patched today or tomorrow!
