### ISSUE TITLE
1.16.5: Getting InventoryCloseEventError, EntityDeathError, EntityDeathEvent and  IndiviualPlayerDropMenu

### ISSUE THREAD

**Issue by MausEsE** [kangarko/Boss#1031]
I´m using boss 4.3.4 and I´m getting troubles with my bosses. When I try to give my boss a custom drop it doesn`t work,
when i try to give my boss a reinforcement it doesn`t work too. **This is my boss error report:**

Error clicking in menu IndividualPlayerDropMenu{}
NullPointerException (Unknown cause)
	 at org.mineacademy.boss.menu.boss.DeathMenu$DropsMenu$PlayerDropsMenu$IndividualPlayerDropMenu.onMenuClose(DeathMenu.java:456)
	 at org.mineacademy.boss.lib.menu.MenuContainerChances.onMenuClose(MenuContainerChances.java:328)
	 at org.mineacademy.boss.lib.menu.MenuContainerChances$1.onClickedInMenu(MenuContainerChances.java:91)
	 at org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1048)
	 at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor16.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------

I don`t know what is happening, I´m currently trying in another minecraft version (1.16.2) and is the same.
PLEASE HELP <3
**My boss plugin file:**
[archive-2022-04-13T234541-0400.tar.gz](https://github.com/kangarko/Boss/files/8486081/archive-2022-04-13T234541-0400.tar.gz)

**Comment by kangarko** [comment]
Thanks, I will fix that.
