### ISSUE TITLE
1.8 " Error clicking in menu IndividualPlayerDropMenu{}"

### ISSUE THREAD

**Issue by Voltikun** [kangarko/Boss#1032]
Hello, when i want to add player drop things to boss for top damager it says " Error clicking in menu IndividualPlayerDropMenu{}" on my console.

Im clicking Death > Drops > Player Drops > Create New > and putting my drop items but when i click return, it says check console, there is problem with menu

Version : 4.3.4

**Comment by ElBananaa** [comment]
Here is the full error provided by the user on discord:
```
------------------------------------[ 16.04.2022 23:57:59 ]-----------------------------------
Boss 4.3.4 encountered a NullPointerException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_311
Plugins: GroupManager v2.0.4-b136, PlaceholderAPI v2.10.6, Websend v2.5.7, Sohbet-Gardiyani v1.0, PlugMan v1.0-SNAPSHOT, NametagEdit v4.4.6, SaveIt v1.1.7, Lockette v1.8.23, SimpleVIPPerks v3.5, antiRedstoneClock v1.0.5, Vulcan v2.6.5, Quests v1.12, BossBarAPI v2.4.1, EnderpearlCooldown v3.3, StaffPlus v3.2.2, Skript v2.2-dev36, AWD v2.3.2, NBTEditor v1.2, ClearLag v3.2.2, LPX v2.7.5-MORTAL, spark v1.8.14, SkQuery v3.6.0-Lime, ProtocolLib v4.3.0, NoCheatPlus v3.16.0-RC-sMD5NET-b1134, eZProtector v4.2.1, FastAsyncWorldEdit v18.06.24-cc97c8d-1145-20.1.15, IPWhitelist v1.7, AutoPickup v3.9, PotionStack v1.6, WildSkript v1.8, DeluxeMenus v1.10.5, LimitCrafting v4.0, UltimateTNT v1.11.2, MelodiaHit v1.0, PlugManX v2.3.0, Vault v1.7.1-b91, PatchPearl v1.6, CrazyCrates v1.7.4.4, Rankup v2.7.4, Item2Chat v4.2.3, HolographicDisplays v2.3.1, VipZero v1.2.4, SkinsRestorer v14.1.15, MetinTasi v1.0, ChestCommands v3.1.4, PlayerVaults v4.1.4, MyCommand v5.1.6, ShopGUIPlus v1.15.0, WorldEdit v6.1.8-SNAPSHOT;cd4729f, Essentials v2.17.1.0, HeadDatabase v4.13.4, LiteBans v2.5.2, Citizens v2.0.16-SNAPSHOT (build 1267), CrazyAuctions v1.2.7, EssentialsChat v2.17.1.0, Mines v6.2.1, PlotSquared v18.10.25-40e7df8-2050, WorldGuard v6.1.3-SNAPSHOT;c904242, Factions v1.6.9.5-U0.6.11-b288, skRayFall v1.9.12, EssentialsProtect v2.17.1.0, CreeperHeal v6.8.1, CommandNPC v1.9.1, EssentialsSpawn v2.17.1.0, RedstoneClockPreventer v1.3.1, TitleManager v2.1.3, CrazyEnchantments v1.7.9.3.2, Jobs v4.10.1, ActionHealth v3.4.1, The Multiverse-Core Plugin, Shopkeepers v2.2.2, ArmorStandTools v2.4.3, Boss v4.3.4, TuSKe v1.8.3-v2, Multiverse-CoreFix v1.2, CommandSigns v1.9.3.3, DeluxeCombat v1.20.8, LeaderHeads v3.1.8.3, Duels v3.3.0
----------------------------------------------------------------------------------------------

More Information: 
Error clicking in menu IndividualPlayerDropMenu{}
NullPointerException (Unknown cause)
	 at org.mineacademy.boss.menu.boss.DeathMenu$DropsMenu$PlayerDropsMenu$IndividualPlayerDropMenu.onMenuClose(DeathMenu.java:456)
	 at org.mineacademy.boss.lib.menu.MenuContainerChances.onMenuClose(MenuContainerChances.java:328)
	 at org.mineacademy.boss.lib.menu.Menu.handleClose(Menu.java:1064)
	 at org.mineacademy.boss.lib.menu.button.ButtonReturnBack.onClickedInMenu(ButtonReturnBack.java:85)
	 at org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1048)
	 at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
----------------------------------------------------------------------------------------------
```

I can also reproduce this issue on a fresh paper 1.18.2 setup with Boss 4.3.4.

**Comment by kangarko** [comment]
Thanks, will get solved in the next release.
