### ISSUE TITLE
Minecraft Version: 1.18.2 Issue ZOMBIE's death error

### ISSUE THREAD

**Issue by MilkAndCereal121** [kangarko/Boss#1048]
whenever i kill a zombie npc i get this error in console

01:07:22] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Boss v4.3.5
java.lang.NullPointerException: Cannot invoke "org.mineacademy.boss.lib.model.Tuple.getKey()" because "tuple" is null
	at org.mineacademy.boss.listener.EntityListener.lambda$onDeath$2(EntityListener.java:341) ~[Boss-4.3.5(1).jar:?]
	at org.mineacademy.boss.listener.BossListener.runIfBoss(BossListener.java:28) ~[Boss-4.3.5(1).jar:?]
	at org.mineacademy.boss.listener.EntityListener.onDeath(EntityListener.java:299) ~[Boss-4.3.5(1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor393.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:878) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1726) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1624) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1452) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:317) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1278) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2540) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2467) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-283]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by kangarko** [comment]
Thanks, I will fix that in 24 hours.
