### ISSUE TITLE
1.8.8: Bosses not loading

### ISSUE THREAD

**Issue by JohneEnderman** [kangarko/Boss#1059]
Im getting the error bellow when i try to load into my server and it deletes the bosses from the menu

------------------------------------[ 17.05.2022 20:54:12 ]-----------------------------------
Boss 4.3.8 encountered an IllegalArgumentException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_272
Plugins: ClansLegendaries v1.4, LuckPerms v5.4.0, WorldEdit v6.1.3;7a097ca, killStats v3.0, PlaceholderAPI v2.11.1, Vault v1.7.3-b131, WorldGuard v6.1.3-SNAPSHOT;c904242, MassiveCore v2.14.0, SCore v1.7.2.7, Citizens v2.0.24-SNAPSHOT (build 1605), PlayerKits v2.22.2, Essentials v2.17.1.0, Prison v3.3.0-alpha.10, EconomyShopGUI v4.5.1, Factions v2.14.0, ChatControl v5.9.1, Boss v4.3.8, KoTH v1.5.1
----------------------------------------------------------------------------------------------

More Information: 
Error loading plugins/Boss/bosses/SkeletonKing.yml: java.lang.IllegalArgumentException: Cannot set to an empty path
IllegalArgumentException Cannot set to an empty path
	 at org.mineacademy.boss.lib.settings.ConfigSection.store(ConfigSection.java:132)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:292)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadFromString(YamlConfig.java:278)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1211)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1171)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:334)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:319)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:225)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:181)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:168)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:132)
	 at org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2303)
	 at org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.mineacademy.boss.BossPlugin$$Lambda$731/0x000000007cb90aa0.run(Unknown Source)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
----------------------------------------------------------------------------------------------

------------------------------------[ 17.05.2022 20:54:12 ]-----------------------------------
Boss 4.3.8 encountered an InvocationTargetException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_272
Plugins: ClansLegendaries v1.4, LuckPerms v5.4.0, WorldEdit v6.1.3;7a097ca, killStats v3.0, PlaceholderAPI v2.11.1, Vault v1.7.3-b131, WorldGuard v6.1.3-SNAPSHOT;c904242, MassiveCore v2.14.0, SCore v1.7.2.7, Citizens v2.0.24-SNAPSHOT (build 1605), PlayerKits v2.22.2, Essentials v2.17.1.0, Prison v3.3.0-alpha.10, EconomyShopGUI v4.5.1, Factions v2.14.0, ChatControl v5.9.1, Boss v4.3.8, KoTH v1.5.1
----------------------------------------------------------------------------------------------

More Information: 
Failed to loadSkeletonKing from bosses
InvocationTargetException (Unknown cause)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:225)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:181)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:168)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:132)
	 at org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2303)
	 at org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.mineacademy.boss.BossPlugin$$Lambda$731/0x000000007cb90aa0.run(Unknown Source)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
IllegalArgumentException Cannot set to an empty path
	 at org.mineacademy.boss.lib.settings.ConfigSection.store(ConfigSection.java:132)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:292)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadFromString(YamlConfig.java:278)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1211)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1171)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:334)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:319)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:225)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:181)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:168)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:132)
	 at org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2303)
	 at org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.mineacademy.boss.BossPlugin$$Lambda$731/0x000000007cb90aa0.run(Unknown Source)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
It says you're running CraftBukkit. Please use Paper for 1.8.8 if you prefer that.

**Comment by JohneEnderman** [comment]
@kangarko I started running Paper 1.8.8 and I'm still having the same issue

**Comment by kangarko** [comment]
Please report the error under the most up to date version because the line numbers have been changed.
