### ISSUE TITLE
Paper 1.8.8: Problem in conversation when making boss after entering Boss name

### ISSUE THREAD

**Issue by bjdag1234** [kangarko/Boss#1060]
Running on Paper 1.8.8 build 445 (also tried on custom tacospigot forks, same issue)

I want to make a new Wither Boss for our pvp zone.

After selecting the wither boss type when making a new boss, entering whatever name yields to:

"Boss // Boss // Oups! There was a problem in this conversation! Please contacct the administrator to review the console for details."

and the error in the console is:

`[05:26:46 WARN]: java.lang.NullPointerException
[05:26:46 WARN]:        at org.mineacademy.boss.lib.ItemUtil.bountifyCapitalized(ItemUtil.java:63)
[05:26:46 WARN]:        at org.mineacademy.boss.menu.boss.SpawningMenu$SpawnEggMenu.<init>(SpawningMenu.java:461)
[05:26:46 WARN]:        at org.mineacademy.boss.menu.boss.SpawningMenu.<init>(SpawningMenu.java:124)
[05:26:46 WARN]:        at org.mineacademy.boss.menu.boss.BossMenu.<init>(BossMenu.java:76)
[05:26:46 WARN]:        at org.mineacademy.boss.menu.boss.BossMenu.showTo(BossMenu.java:146)
[05:26:46 WARN]:        at org.mineacademy.boss.prompt.CreateBossPrompt.displayMenu(CreateBossPrompt.java:53)
[05:26:46 WARN]:        at org.mineacademy.boss.prompt.CreateBossPrompt.displayMenu(CreateBossPrompt.java:12)
[05:26:46 WARN]:        at org.mineacademy.boss.prompt.CreatePrompt.onConversationEnd(CreatePrompt.java:149)
[05:26:46 WARN]:        at org.mineacademy.boss.lib.conversation.SimpleConversation.conversationAbandoned(SimpleConversation.java:108)
[05:26:46 WARN]:        at org.bukkit.conversations.Conversation.abandon(Conversation.java:278)
[05:26:46 WARN]:        at org.mineacademy.boss.lib.conversation.SimpleConversation$CustomConversation.outputNextPrompt(SimpleConversation.java:319)
[05:26:46 WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:230)
[05:26:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58)
[05:26:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1126)
[05:26:46 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection$5.evaluate(PlayerConnection.java:1015)
[05:26:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24)
[05:26:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789)
[05:26:46 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[05:26:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[05:26:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[05:26:46 WARN]:        at java.lang.Thread.run(Thread.java:748)`

I want to be able to use this plugin to make custom bosses for my 1.8.8 server. Please note that we can't let go of 1.8.8.

**Comment by kangarko** [comment]
Thanks, I will fix that :)
