### ISSUE TITLE
1.8.8: Bosses not loading

### ISSUE THREAD

**Issue by JohneEnderman** [kangarko/Boss#1073]
Im getting the error bellow when i try to load into my server and it deletes the bosses from the menu

```
------------------------------------[ 30.05.2022 10:33:43 ]-----------------------------------
Boss 4.3.9 encountered an IllegalArgumentException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_272
Plugins: ClansLegendaries v1.4, NoCheatPlus v3.16.0-RC-sMD5NET-b1134, LuckPerms v5.4.0, WorldEdit v6.1.3;7a097ca, killStats v3.0, PlaceholderAPI v2.11.1, AdvancedHCFAbilities v3.0-FINAL, EpicBoss_Gold_Edition v0.1.4, KoTH v2.0.4, Vault v1.7.3-b131, WorldGuard v6.1.3-SNAPSHOT;c904242, MassiveCore v2.14.0, SCore v1.7.2.7, Citizens v2.0.24-SNAPSHOT (build 1605), PlayerKits v2.22.2, Essentials v2.17.1.0, Prison v3.3.0-alpha.10, EconomyShopGUI v4.5.1, Factions v2.14.0, CombatTagPlus v1.3.1, Boss v4.3.9
----------------------------------------------------------------------------------------------

More Information: 
Error loading plugins/Boss/bosses/SkeletonKing.yml: java.lang.IllegalArgumentException: Cannot set to an empty path
IllegalArgumentException Cannot set to an empty path
	 at org.mineacademy.boss.lib.settings.ConfigSection.store(ConfigSection.java:132)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:292)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadFromString(YamlConfig.java:278)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1211)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1171)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:336)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:321)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:225)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:181)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:168)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:132)
	 at org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2314)
	 at org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.mineacademy.boss.BossPlugin$$Lambda$1579/0x0000000050421630.run(Unknown Source)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
----------------------------------------------------------------------------------------------
```

**Comment by ElBananaa** [comment]
Hey, please update to Boss 4.3.11 and let us know if that changes anything.

**Comment by JohneEnderman** [comment]
------------------------------------[ 05.06.2022 11:52:57 ]-----------------------------------
Boss 4.3.11 encountered an IllegalArgumentException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_272
Plugins: ClansLegendaries v1.4, LuckPerms v5.4.0, WorldEdit v6.1.3;7a097ca, Skript v2.1.2, killStats v3.0, PlaceholderAPI v2.11.1, PvPLevels v2.2.4, AdvancedHCFAbilities v3.0-FINAL, EpicBoss_Gold_Edition v0.1.4, KoTH v2.0.4, Vault v1.7.3-b131, ArmorSetEffects v2.2.4, LPC v3.1.0, WorldGuard v6.1.3-SNAPSHOT;c904242, MassiveCore v2.14.0, SCore v1.7.2.7, Citizens v2.0.24-SNAPSHOT (build 1605), PlayerKits v2.22.2, Essentials v2.17.1.0, Prison v3.3.0-alpha.10, EconomyShopGUI v4.5.1, Factions v2.14.0, CombatTagPlus v1.3.1, Boss v4.3.11
----------------------------------------------------------------------------------------------

More Information: 
Error loading plugins/Boss/bosses/skeletonking.yml: java.lang.IllegalArgumentException: Cannot set to an empty path
IllegalArgumentException Cannot set to an empty path
	 at org.mineacademy.boss.lib.settings.ConfigSection.store(ConfigSection.java:132)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:292)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.convertMapsToSections(YamlConfig.java:290)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadFromString(YamlConfig.java:278)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1211)
	 at org.mineacademy.boss.lib.settings.FileConfig.load(FileConfig.java:1171)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:336)
	 at org.mineacademy.boss.model.Boss.<init>(Boss.java:321)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:225)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadOrCreateItem(ConfigItems.java:181)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:168)
	 at org.mineacademy.boss.lib.settings.ConfigItems.loadItems(ConfigItems.java:132)
	 at org.mineacademy.boss.model.Boss.loadBosses(Boss.java:2317)
	 at org.mineacademy.boss.BossPlugin.lambda$onReloadablesStart$0(BossPlugin.java:138)
	 at org.mineacademy.boss.BossPlugin$$Lambda$3201/0x000000009b421110.run(Unknown Source)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
----------------------------------------------------------------------------------------------

**Comment by JohneEnderman** [comment]
the text above is from the latest version of boss

**Comment by ElBananaa** [comment]
Alright, it seems like there's an issue with the Skeleton King boss. Make a backup of your boss folder then stop your server and delete it. It should generate a proper file.

**Comment by ElBananaa** [comment]
Hey, @JohneEnderman Any news about this? Can I close the issue?

**Comment by ElBananaa** [comment]
We didn't receive any answers for more than a week.
I'm closing this issue.

Feel free to keep commenting down below if you still need help, or open another issue.
