### ISSUE TITLE
1.19: boss:b menu error switch page

### ISSUE THREAD

**Issue by WolverStones** [kangarko/Boss#1083]
```
WolverStone issued server command: /boss:b menu
[18:38:01 ERROR]: Boss 4.4.1 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file.
[18:38:01 INFO]: org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in WardenSpawnTracker or its superclasses
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:209)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:186)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1543)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:631)
[18:38:01 INFO]: at Boss
-4.4.1.jar//org.mineacademy.boss.lib.menu.MenuPagged.updatePage(MenuPagged.java:318)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.menu.MenuPagged.access$200(MenuPagged.java:35)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.menu.MenuPagged$2.onClickedInMenu(MenuPagged.java:296)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1046)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.menu.MenuPagged.onButtonClick(MenuPagged.java:467)
[18:38:01 INFO]: at Boss-4.4.1.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
[18:38:01 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor40.execute(Unknown Source)
[18:38:01 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[18:38:01 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[18:38:01 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:38:01 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
[18:38:01 INFO]: [Boss] !-----------------------------------------------------!
[18:38:01 INFO]: [Boss] Error clicking in menu CreateMenu{}
[18:38:01 INFO]: [Boss] !-----------------------------------------------------!
```

[error.log](https://github.com/kangarko/Boss/files/9041272/error.log)

**Comment by kangarko** [comment]
Thanks, will be patched.
