### ISSUE TITLE
1.19: menu broken

### ISSUE THREAD

**Issue by TannerK420** [kangarko/Boss#1087]
I can't go to page 2 in boss create menu

`[15:16:25 ERROR]: Boss 4.4.1 encountered a ReflectionException! Please check your error.log and report this issue with the information in that file.
[15:16:25 INFO]: org.mineacademy.boss.lib.ReflectionUtil$ReflectionException: No such field j in WardenSpawnTracker or its superclasses
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:209)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.ReflectionUtil.getFieldContent(ReflectionUtil.java:186)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.remain.Remain.updateInventoryTitle(Remain.java:1543)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.PlayerUtil.updateInventoryTitle(PlayerUtil.java:631)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.menu.MenuPagged.updatePage(MenuPagged.java:318)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.menu.MenuPagged.access$200(MenuPagged.java:35)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.menu.MenuPagged$2.onClickedInMenu(MenuPagged.java:296)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1046)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.menu.MenuPagged.onButtonClick(MenuPagged.java:467)
[15:16:25 INFO]: at Boss-4.4.1 (1).jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
[15:16:25 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor908.execute(Unknown Source)
[15:16:25 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[15:16:25 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:16:25 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:16:25 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664)
[15:16:25 INFO]: [Boss] 7!-----------------------------------------------------!
[15:16:25 INFO]: [Boss]  cError clicking in menu CreateMenu{}
[15:16:25 INFO]: [Boss] 7!-----------------------------------------------------!
`

**Comment by matipoirierg** [comment]
Can cofnirm this, multiple menus are not working. 
https://pastebin.com/Pbnd7vpa

**Comment by LucidAPs** [comment]
Same here
https://nekobin.com/pocabonuya

**Comment by kangarko** [comment]
Thank you, I will fix that asap!
