### ISSUE TITLE
Boss on death / Commands

### ISSUE THREAD

**Issue by harry0198** [kangarko/Boss#116]
I've selected my boss on death to spawn another boss and it doesn't happen, not sure what's up with that.

**Comment by harry0198** [comment]
This is my error log
[20:13:05] [Server thread/INFO]: BOSS // Boss 1.6.15 encountered a cOm9! Please check your error.log and report this issue with the information in that file.
[20:13:05] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Boss v1.6.15
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:394) [server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:387) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1112) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1609) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-596221b-9a1fc1e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: me.kangarko.boss.final. .cOm9: Report / Cannot spawn reinforcement as the Boss 'Warden 1' does not exist
at me.kangarko.boss.final. .com2.protected(SourceFile:20) ~[Boss-1.6.15.jar:?]
at me.kangarko.boss.final. .aF.onDeath(SourceFile:147) ~[Boss-1.6.15.jar:?]
at sun.reflect.GeneratedMethodAccessor419.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-596221b-9a1fc1e]
... 22 more

**Comment by kangarko** [comment]
Seems your boss file is outdated (Warden 1 should be Warden, 1), edit it according to this format:

![a](https://i.imgur.com/HOZoigG.png)
