### ISSUE TITLE
WineSpigot: 1.8.8: Unable to load plugin

### ISSUE THREAD

**Issue by Zyro746** [kangarko/Boss#1168]
Hi,  I recently purchased boss off of builtbybit for my server. When trying to start it throws a class error. Any help would be appreciated. If you believe it's a WineSpigot issue please let me know and I'll pass it along to Golfing8 who made this fork. 
------------------------------------[ 08.06.2023 21:27:24 ]-----------------------------------
Boss 4.7.9 encountered a NoClassDefFoundError
Running WineSpigot 1.8.8-R0.2-SNAPSHOT and Java 1.8.0_312
Plugins: Verus v1.0, PlaceholderAPI v2.11.3, PlugMan v1.0-SNAPSHOT, HolographicDisplays v3.0.2, Dracma v2.0.4-SNAPSHOT, DeluxeTags v1.8.2-Release, ViaVersion v4.6.2, CoreProtect v2.12.0, LuckPerms v5.4.79, spark v1.10.34, WorldBorder v1.8.4, BuycraftX v12.0.8, Votifier v2.7.3, ProtocolLib v5.0.0, Vouchers v1.8.17-RELEASE, FastAsyncWorldEdit v21.03.26-5ff3a9b-1286-22.3.9, ManticLib v1.0.37.0, PlugManX v2.3.2, Vault v1.5.5-b47, Factions v1.6.9.5-U0.5.18-b${build.number}, BlueSlimeCore v2.9.2.364, InfiniteKoth v1.1.1, WorldEdit v6.1.9-SNAPSHOT-WX, SuperVotes v1.0.7, Essentials v2.20.0, LPX v3.3.0, LiteBans v2.12.2, EssentialsWarpGUI v3.0, ManticVanillaEnchants v1.3.1, PremiumDonationEffects v1.0.1-SNAPSHOT, Multiverse-Core v4.3.1-b861, DeluxeChat v1.16.2, Citizens v2.0.16-SNAPSHOT (build 1267), DiscordSRV v1.26.2, DeluxeMenus v1.13.3-Release, TAB v3.3.2, Boss v4.7.9, WorldGuard v6.2.2-SNAPSHOT, CloudCrates v2.81, ajParkour v2.12.10, CrazyEnvoys v1.4.17.3, EssentialsSpawn v2.20.0, InteractiveChat v4.2.6.1, ManticDarkzone v1.1.1, SilkSpawners v7.3.0, CombatTagPlus v1.3.1, Duels v3.5.3, PocketOceans v1.2, ShopGUIPlus v1.85.0, ShopGUIPlusSilkSpawnersBridge v1.4.0, ManticHoes v1.5.4, FactionsKore v1.0, ManticSwords v1.5.4, ManticSets v1.0.2
----------------------------------------------------------------------------------------------

More Information: 
Error while loading Boss dependencies!
NoClassDefFoundError com/onarandombox/MultiverseCore/MultiverseCore
	 at org.mineacademy.boss.lib.model.MultiverseHook.<init>(HookManager.java:2018)
	 at org.mineacademy.boss.lib.model.HookManager.loadDependencies(HookManager.java:246)
	 at org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:297)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:378)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320)
ClassNotFoundException com.onarandombox.MultiverseCore.MultiverseCore
	 at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	 at org.mineacademy.boss.lib.model.MultiverseHook.<init>(HookManager.java:2018)
	 at org.mineacademy.boss.lib.model.HookManager.loadDependencies(HookManager.java:246)
	 at org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:297)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:378)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320)
----------------------------------------------------------------------------------------------

------------------------------------[ 08.06.2023 21:27:24 ]-----------------------------------
Boss 4.7.9 encountered a NoClassDefFoundError
Running WineSpigot 1.8.8-R0.2-SNAPSHOT and Java 1.8.0_312
Plugins: Verus v1.0, PlaceholderAPI v2.11.3, PlugMan v1.0-SNAPSHOT, HolographicDisplays v3.0.2, Dracma v2.0.4-SNAPSHOT, DeluxeTags v1.8.2-Release, ViaVersion v4.6.2, CoreProtect v2.12.0, LuckPerms v5.4.79, spark v1.10.34, WorldBorder v1.8.4, BuycraftX v12.0.8, Votifier v2.7.3, ProtocolLib v5.0.0, Vouchers v1.8.17-RELEASE, FastAsyncWorldEdit v21.03.26-5ff3a9b-1286-22.3.9, ManticLib v1.0.37.0, PlugManX v2.3.2, Vault v1.5.5-b47, Factions v1.6.9.5-U0.5.18-b${build.number}, BlueSlimeCore v2.9.2.364, InfiniteKoth v1.1.1, WorldEdit v6.1.9-SNAPSHOT-WX, SuperVotes v1.0.7, Essentials v2.20.0, LPX v3.3.0, LiteBans v2.12.2, EssentialsWarpGUI v3.0, ManticVanillaEnchants v1.3.1, PremiumDonationEffects v1.0.1-SNAPSHOT, Multiverse-Core v4.3.1-b861, DeluxeChat v1.16.2, Citizens v2.0.16-SNAPSHOT (build 1267), DiscordSRV v1.26.2, DeluxeMenus v1.13.3-Release, TAB v3.3.2, Boss v4.7.9, WorldGuard v6.2.2-SNAPSHOT, CloudCrates v2.81, ajParkour v2.12.10, CrazyEnvoys v1.4.17.3, EssentialsSpawn v2.20.0, InteractiveChat v4.2.6.1, ManticDarkzone v1.1.1, SilkSpawners v7.3.0, CombatTagPlus v1.3.1, Duels v3.5.3, PocketOceans v1.2, ShopGUIPlus v1.85.0, ShopGUIPlusSilkSpawnersBridge v1.4.0, ManticHoes v1.5.4, FactionsKore v1.0, ManticSwords v1.5.4, ManticSets v1.0.2
----------------------------------------------------------------------------------------------
NoClassDefFoundError com/onarandombox/MultiverseCore/MultiverseCore
	 at org.mineacademy.boss.lib.model.MultiverseHook.<init>(HookManager.java:2018)
	 at org.mineacademy.boss.lib.model.HookManager.loadDependencies(HookManager.java:246)
	 at org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:297)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:378)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320)
ClassNotFoundException com.onarandombox.MultiverseCore.MultiverseCore
	 at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	 at org.mineacademy.boss.lib.model.MultiverseHook.<init>(HookManager.java:2018)
	 at org.mineacademy.boss.lib.model.HookManager.loadDependencies(HookManager.java:246)
	 at org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:297)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:321)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:378)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Something's wrong with com/onarandombox/MultiverseCore/**MultiverseCore**, please update that plugin or consult with them first.
