### ISSUE TITLE
1.16.5: Plugin not starting up

### ISSUE THREAD

**Issue by Chumb3x** [kangarko/Boss#1176]
Hello, so the plugin is not starting up. Here is the error I am getting in the console:

```
[11:59:16 INFO]: [Boss] Loading 1 libraries... please wait
[11:59:16 ERROR]: Could not load 'plugins/Boss-4.8.8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.AbstractMethodError: Receiver class org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayoutEx does not define or inherit an implementation of the resolved method 'abstract java.util.List getChecksumAlgorithmFactories()' of interface org.bukkit.craftbukkit.libs.org.eclipse.aether.spi.connector.layout.RepositoryLayout.
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:395) ~[server.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[server.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1079) ~[server.jar:git-Purpur-"53ac6a9"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[server.jar:git-Purpur-"53ac6a9"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory$Maven2RepositoryLayoutEx does not define or inherit an implementation of the resolved method 'abstract java.util.List getChecksumAlgorithmFactories()' of interface org.bukkit.craftbukkit.libs.org.eclipse.aether.spi.connector.layout.RepositoryLayout.
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:230) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.craftbukkit.libs.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:97) ~[server.jar:git-Purpur-"53ac6a9"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[server.jar:git-Purpur-"53ac6a9"]
        ... 7 more
```

**Comment by kangarko** [comment]
Redownload the jar and try loading via Paper not Purpur

**Comment by Chumb3x** [comment]
I re-downloaded the jar, but nothing changed. Also, I will not be switching to Paper. Purpur = Paper + optimizations

**Comment by kangarko** [comment]
Looks like a checksum issue or a library download problem, that is why I asked you to do one test with Paper to see if the problem goes away because I have no idea how Purpur manages those things

**Comment by Chumb3x** [comment]
It worked with paper and then when I switched back to purpur it worked there after it loaded on paper, so thanks a lot
