### ISSUE TITLE
1.19.4 - Item is null (console error)

### ISSUE THREAD

**Issue by Lecer69** [kangarko/Boss#1197]
1. Create a boss (Enderman)
2. Spawn it
3. Check the console for warns/errors

```
[01:22:11 WARN]: [Boss] Task #6844 for Boss v4.8.12 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "item" is null
        at org.mineacademy.boss.lib.remain.CompEquipmentSlot.applyTo(CompEquipmentSlot.java:158) ~[Boss-4.8.12.jar:?]
        at org.mineacademy.boss.lib.remain.CompEquipmentSlot.clear(CompEquipmentSlot.java:134) ~[Boss-4.8.12.jar:?]
        at org.mineacademy.boss.model.Boss.lambda$applyProperties$0(Boss.java:977) ~[Boss-4.8.12.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by kangarko** [comment]
Thanks, will be patched.
