### ISSUE TITLE
1.8.8: Worldguard support error

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1209]
Error when start Boss in 1.8.8 with worldguard (V6.2), maybe without working on the features too. 
(WorldGuard 6.2 it's the last version that works WG in 1.8)

```[19:39:44 INFO]: [Boss] Loading Boss v4.8.16
[19:39:44 ERROR]: com/sk89q/worldguard/WorldGuard initializing Boss v4.8.16 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.register(WorldGuardHook.java:50) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.init(WorldGuardHook.java:23) ~[?:?]
        at org.mineacademy.boss.BossPlugin.onPluginLoad(BossPlugin.java:98) ~[?:?]
        at org.mineacademy.boss.lib.plugin.SimplePlugin.onLoad(SimplePlugin.java:226) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:303) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 9 more```

-----------

Other errors appers when some boss attacks you or something like that:

-----------

```[20:07:56 ERROR]: Could not pass event EntityTargetLivingEntityEvent to Boss v4.8.16
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.setGoalTarget(EntityInsentient.java:110) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:86) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:69) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:477) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1649) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:339) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntitySkeleton.m(EntitySkeleton.java:110) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1513) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1780) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1747) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1576) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:967) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.canTarget(WorldGuardHook.java:54) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.canTarget(WorldGuardHook.java:36) ~[?:?]
        at org.mineacademy.boss.model.Boss.canTarget(Boss.java:2638) ~[?:?]
        at org.mineacademy.boss.listener.EntityListener.onTarget(EntityListener.java:573) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        ... 25 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.canTarget(WorldGuardHook.java:54) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.canTarget(WorldGuardHook.java:36) ~[?:?]
        at org.mineacademy.boss.model.Boss.canTarget(Boss.java:2638) ~[?:?]
        at org.mineacademy.boss.listener.EntityListener.onTarget(EntityListener.java:573) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        ... 25 more
[20:08:07 ERROR]: Could not pass event EntityTargetLivingEntityEvent to Boss v4.8.16
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.setGoalTarget(EntityInsentient.java:110) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:86) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:69) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:477) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1649) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:339) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntitySkeleton.m(EntitySkeleton.java:110) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1513) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:194) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1780) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1747) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1576) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:967) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.canTarget(WorldGuardHook.java:54) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.canTarget(WorldGuardHook.java:36) ~[?:?]
        at org.mineacademy.boss.model.Boss.canTarget(Boss.java:2638) ~[?:?]
        at org.mineacademy.boss.listener.EntityListener.onTarget(EntityListener.java:573) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        ... 25 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.canTarget(WorldGuardHook.java:54) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.canTarget(WorldGuardHook.java:36) ~[?:?]
        at org.mineacademy.boss.model.Boss.canTarget(Boss.java:2638) ~[?:?]
        at org.mineacademy.boss.listener.EntityListener.onTarget(EntityListener.java:573) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        ... 25 more
[20:08:08 INFO]: [Boss] !-----------------------------------------------------!
[20:08:08 INFO]: [Boss]  Error running skill 'Minions'!
[20:08:08 INFO]: [Boss]  Boss: russeou
[20:08:08 INFO]: [Boss]  Error: com/sk89q/worldguard/WorldGuard
[20:08:08 INFO]: [Boss] !-----------------------------------------------------!
[20:08:08 ERROR]: Boss 4.8.16 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file. Running PandaSpigot 1.8.8-R0.1-SNAPSHOT and Java 17.0.8.1
[20:08:08 ERROR]: Boss 4.8.16 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file. Running PandaSpigot 1.8.8-R0.1-SNAPSHOT and Java 17.0.8.1
[20:08:08 WARN]: [Boss] Task #145 for Boss v4.8.16 generated an exception
org.mineacademy.boss.lib.exception.FoException: Report: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at org.mineacademy.boss.lib.remain.Remain.sneaky(Remain.java:2727) ~[?:?]
        at org.mineacademy.boss.lib.Common.throwError(Common.java:1445) ~[?:?]
        at org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:129) ~[?:?]
        at org.mineacademy.boss.task.TaskBehavior.run(TaskBehavior.java:89) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:890) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.canTarget(WorldGuardHook.java:54) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.canTarget(WorldGuardHook.java:36) ~[?:?]
        at org.mineacademy.boss.model.Boss.canTarget(Boss.java:2638) ~[?:?]
        at org.mineacademy.boss.skill.AbstractTargetSkill.execute(AbstractTargetSkill.java:34) ~[?:?]
        at org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:126) ~[?:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at org.mineacademy.boss.hook.BossTargetFlag.canTarget(WorldGuardHook.java:54) ~[?:?]
        at org.mineacademy.boss.hook.WorldGuardHook.canTarget(WorldGuardHook.java:36) ~[?:?]
        at org.mineacademy.boss.model.Boss.canTarget(Boss.java:2638) ~[?:?]
        at org.mineacademy.boss.skill.AbstractTargetSkill.execute(AbstractTargetSkill.java:34) ~[?:?]
        at org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:126) ~[?:?]
        ... 9 more```

**Comment by kangarko** [comment]
Thanks, unfortunately 1.8.8 is unsupported with that flag and WG. I will fix the error.
