### ISSUE TITLE
1.8.8: Console Flood on changing quantity in Boss Menu

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1232]
Spigot Version: PandaSpigot 1.8.8
Video example: https://youtu.be/9Q1qdp597fY

The problem is when I change quantity in boss menu, can be whatever quantity in whatever menu, always flood my console with this:

```[16:41:20 WARN]: java.lang.reflect.InvocationTargetException
[16:41:20 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
[16:41:20 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:41:20 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:41:20 WARN]:        at me.saif.betterenderchests.lang.inventory.impl.OpenEnderchestPacketModifier_1_12_Below.modifyPacket(OpenEnderchestPacketModifier_1_12_Below.java:50)
[16:41:20 WARN]:        at me.saif.betterenderchests.lang.inventory.packetinterceptor.PacketInterceptor$1.write(PacketInterceptor.java:79)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:41:20 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:41:20 WARN]:        at me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:35)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[16:41:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:41:20 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:41:20 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:41:20 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:41:20 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.lambda$writePacket$5(NetworkManager.java:374)
[16:41:20 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:41:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:41:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:41:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:41:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:41:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:41:20 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:41:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[16:41:20 WARN]: Caused by: net.minecraft.server.v1_8_R3.ChatMessageException: Error parsing: TranslatableComponent{key='Editing quantity set to 0.5%', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}: Unsupported format: '%'

[16:41:20 WARN]:        at net.minecraft.server.v1_8_R3.ChatMessage.b(ChatMessage.java:95)
[16:41:20 WARN]:        at net.minecraft.server.v1_8_R3.ChatMessage.g(ChatMessage.java:52)
[16:41:20 WARN]:        at net.minecraft.server.v1_8_R3.ChatMessage.getText(ChatMessage.java:169)
[16:41:20 WARN]:        ... 28 more
[16:41:21 WARN]: java.lang.reflect.InvocationTargetException
[16:41:21 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
[16:41:21 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:41:21 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:41:21 WARN]:        at me.saif.betterenderchests.lang.inventory.impl.OpenEnderchestPacketModifier_1_12_Below.modifyPacket(OpenEnderchestPacketModifier_1_12_Below.java:50)
[16:41:21 WARN]:        at me.saif.betterenderchests.lang.inventory.packetinterceptor.PacketInterceptor$1.write(PacketInterceptor.java:79)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:41:21 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:41:21 WARN]:        at me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:35)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[16:41:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:41:21 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:41:21 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:41:21 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:41:21 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.lambda$writePacket$5(NetworkManager.java:374)
[16:41:21 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:41:21 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:41:21 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:41:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:41:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:41:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:41:21 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:41:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[16:41:21 WARN]: Caused by: net.minecraft.server.v1_8_R3.ChatMessageException: Error parsing: TranslatableComponent{key='Editing quantity set to 0.1%', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}: Unsupported format: '%'

[16:41:21 WARN]:        at net.minecraft.server.v1_8_R3.ChatMessage.b(ChatMessage.java:95)
[16:41:21 WARN]:        at net.minecraft.server.v1_8_R3.ChatMessage.g(ChatMessage.java:52)
[16:41:21 WARN]:        at net.minecraft.server.v1_8_R3.ChatMessage.getText(ChatMessage.java:169)
[16:41:21 WARN]:        ... 28 more```

**Comment by kangarko** [comment]
This issue is actually raised by betterenderchests, you need to speak with their team instead.
