### ISSUE TITLE
1.20.4:  "The menu has only 0 pages, not 1!"

### ISSUE THREAD

**Issue by troyamelotte** [kangarko/Boss#1245]
I just installed the boss plugin & am getting "Boss 4.11.4 encountered a FoException.  The menu has only 0 pages, not 1!"
Here's the whole error log

```
------------------------------------[ 29.04.2024 20:34:34 ]-----------------------------------
Boss 4.11.4 encountered a FoException
Running Purpur 1.20.4-R0.1-SNAPSHOT and Java 17.0.10
Plugins: ViaVersion v4.9.2, LuckPerms v5.4.102, Vault v1.7.3-b131, FastAsyncWorldEdit v2.9.3-SNAPSHOT-719;8b59741, ProtocolLib v5.2.0-SNAPSHOT-679, WorldGuard v7.0.9+5934e49, PlaceholderAPI v2.11.5, VoidGen v2.2.1, Citizens v2.0.33-SNAPSHOT (build 3379), ViaBackwards v4.9.1, Essentials v2.21.0-dev+25-fbfd7e9, Multiverse-Core v4.3.12, ModelEngine vR4.0.4, floodgate v2.2.2-SNAPSHOT (b88-94eabd7), ViaRewind v3.0.6-SNAPSHOT, NexEngine v2.2.12, SuperVanish v6.2.18, BlueSlimeCore v2.9.4.377, FurnitureLib v3.1.5, Oraxen v1.172.0, Votifier v2.7.3, Skript v2.6.4, DecentHolograms v2.8.6, BanManager v7.9.0, BasementLib v1.3.43, CoreProtect v22.2, TAB v4.1.2, CoinsEngine v2.1.1, LevelledMobs v3.15.3 b834, SkinsRestorer v15.0.11, CombatLogX v11.4.0.1.1193, PlayerAuctions v1.27.3, DiceFurniture v3.8.1, DeluxeMenus v1.14.0-Release, ChatEmojis v2.3.4, FreedomChat v1.5.2, Infiniteannouncements v2.4.0, spark v1.10.34, CrazyVouchers v3.1.5, SuperbVote v0.5.5, skUtilities v0.9.2, EssentialsSpawn v2.21.0-dev+25-fbfd7e9, LPC v3.6.0, Sellwand v1.5.10, InteractionVisualizer v1.18.8.0, EasyCommandBlocker v1.8.1, ForcePack v1.3.3, BlockParticles v1.11.1-RELEASE, Boss v4.11.4, OneBlock v1.0.24, skRayFall v1.9.28, ClearLag v3.2.2, eGlow v3.2.8, Analyse v2.0.10, VelocityReport v3.10.5, ExcellentCrates v5.0.0, LitMinions v2.77, SmoothSleep v2.11.2, PermSk v1.1.1, Dungeons v3.4.6, BuycraftX v12.0.8, SetModelData v1.0.0, ajLeaderboards v2.8.0, DeathMessages v1.4.15, InteractiveChat v4.2.9.0, WorldBorder v1.9.10 (beta), DeluxeTags v1.8.2-Release, Orebfuscator v5.4.3, CMILib v1.4.4.9, UltraCosmetics v3.4.2, Dualhorse v1.4.1, AutoTool v1.1.3
----------------------------------------------------------------------------------------------

More Information: 
The menu has only 0 pages, not 1!
FoException Report: The menu has only 0 pages, not 1!
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.Valid.checkBoolean(Valid.java:90)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuPagged.getCurrentPageItems(MenuPagged.java:575)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuPagged.getItemAt(MenuPagged.java:498)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.compileItems(Menu.java:597)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.displayTo(Menu.java:430)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.button.ButtonMenu.onClickedInMenu(ButtonMenu.java:148)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1120)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor831.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
----------------------------------------------------------------------------------------------


------------------------------------[ 29.04.2024 20:34:46 ]-----------------------------------
Boss 4.11.4 encountered a FoException
Running Purpur 1.20.4-R0.1-SNAPSHOT and Java 17.0.10
Plugins: ViaVersion v4.9.2, LuckPerms v5.4.102, Vault v1.7.3-b131, FastAsyncWorldEdit v2.9.3-SNAPSHOT-719;8b59741, ProtocolLib v5.2.0-SNAPSHOT-679, WorldGuard v7.0.9+5934e49, PlaceholderAPI v2.11.5, VoidGen v2.2.1, Citizens v2.0.33-SNAPSHOT (build 3379), ViaBackwards v4.9.1, Essentials v2.21.0-dev+25-fbfd7e9, Multiverse-Core v4.3.12, ModelEngine vR4.0.4, floodgate v2.2.2-SNAPSHOT (b88-94eabd7), ViaRewind v3.0.6-SNAPSHOT, NexEngine v2.2.12, SuperVanish v6.2.18, BlueSlimeCore v2.9.4.377, FurnitureLib v3.1.5, Oraxen v1.172.0, Votifier v2.7.3, Skript v2.6.4, DecentHolograms v2.8.6, BanManager v7.9.0, BasementLib v1.3.43, CoreProtect v22.2, TAB v4.1.2, CoinsEngine v2.1.1, LevelledMobs v3.15.3 b834, SkinsRestorer v15.0.11, CombatLogX v11.4.0.1.1193, PlayerAuctions v1.27.3, DiceFurniture v3.8.1, DeluxeMenus v1.14.0-Release, ChatEmojis v2.3.4, FreedomChat v1.5.2, Infiniteannouncements v2.4.0, spark v1.10.34, CrazyVouchers v3.1.5, SuperbVote v0.5.5, skUtilities v0.9.2, EssentialsSpawn v2.21.0-dev+25-fbfd7e9, LPC v3.6.0, Sellwand v1.5.10, InteractionVisualizer v1.18.8.0, EasyCommandBlocker v1.8.1, ForcePack v1.3.3, BlockParticles v1.11.1-RELEASE, Boss v4.11.4, OneBlock v1.0.24, skRayFall v1.9.28, ClearLag v3.2.2, eGlow v3.2.8, Analyse v2.0.10, VelocityReport v3.10.5, ExcellentCrates v5.0.0, LitMinions v2.77, SmoothSleep v2.11.2, PermSk v1.1.1, Dungeons v3.4.6, BuycraftX v12.0.8, SetModelData v1.0.0, ajLeaderboards v2.8.0, DeathMessages v1.4.15, InteractiveChat v4.2.9.0, WorldBorder v1.9.10 (beta), DeluxeTags v1.8.2-Release, Orebfuscator v5.4.3, CMILib v1.4.4.9, UltraCosmetics v3.4.2, Dualhorse v1.4.1, AutoTool v1.1.3
----------------------------------------------------------------------------------------------

More Information: 
The menu has only 0 pages, not 1!
FoException Report: The menu has only 0 pages, not 1!
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.Valid.checkBoolean(Valid.java:90)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuPagged.getCurrentPageItems(MenuPagged.java:575)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuPagged.getItemAt(MenuPagged.java:498)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.compileItems(Menu.java:597)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.displayTo(Menu.java:430)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.button.ButtonMenu.onClickedInMenu(ButtonMenu.java:148)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1120)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor831.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
----------------------------------------------------------------------------------------------


------------------------------------[ 29.04.2024 23:54:14 ]-----------------------------------
Boss 4.11.4 encountered a FoException
Running Purpur 1.20.4-R0.1-SNAPSHOT and Java 17.0.10
Plugins: ViaVersion v4.9.2, LuckPerms v5.4.102, Vault v1.7.3-b131, FastAsyncWorldEdit v2.9.3-SNAPSHOT-719;8b59741, ProtocolLib v5.2.0-SNAPSHOT-679, WorldGuard v7.0.9+5934e49, PlaceholderAPI v2.11.5, VoidGen v2.2.1, Citizens v2.0.33-SNAPSHOT (build 3379), ViaBackwards v4.9.1, Essentials v2.21.0-dev+25-fbfd7e9, Multiverse-Core v4.3.12, ModelEngine vR4.0.4, floodgate v2.2.2-SNAPSHOT (b88-94eabd7), ViaRewind v3.0.6-SNAPSHOT, NexEngine v2.2.12, SuperVanish v6.2.18, BlueSlimeCore v2.9.4.377, FurnitureLib v3.1.5, Oraxen v1.172.0, Votifier v2.7.3, Skript v2.6.4, DecentHolograms v2.8.6, BanManager v7.9.0, BasementLib v1.3.43, CoreProtect v22.2, TAB v4.1.2, CoinsEngine v2.1.1, LevelledMobs v3.15.3 b834, SkinsRestorer v15.0.11, CombatLogX v11.4.0.1.1193, PlayerAuctions v1.27.3, DiceFurniture v3.8.1, DeluxeMenus v1.14.0-Release, ChatEmojis v2.3.4, FreedomChat v1.5.2, Infiniteannouncements v2.4.0, spark v1.10.34, CrazyVouchers v3.1.5, SuperbVote v0.5.5, skUtilities v0.9.2, EssentialsSpawn v2.21.0-dev+25-fbfd7e9, LPC v3.6.0, Sellwand v1.5.10, InteractionVisualizer v1.18.8.0, EasyCommandBlocker v1.8.1, ForcePack v1.3.3, BlockParticles v1.11.1-RELEASE, Boss v4.11.4, OneBlock v1.0.24, skRayFall v1.9.28, ClearLag v3.2.2, eGlow v3.2.8, Analyse v2.0.10, VelocityReport v3.10.5, ExcellentCrates v5.0.0, LitMinions v2.77, SmoothSleep v2.11.2, PermSk v1.1.1, Dungeons v3.4.6, BuycraftX v12.0.8, SetModelData v1.0.0, ajLeaderboards v2.8.0, DeathMessages v1.4.15, InteractiveChat v4.2.9.0, WorldBorder v1.9.10 (beta), DeluxeTags v1.8.2-Release, Orebfuscator v5.4.3, CMILib v1.4.4.9, UltraCosmetics v3.4.2, Dualhorse v1.4.1, AutoTool v1.1.3
----------------------------------------------------------------------------------------------

More Information: 
The menu has only 0 pages, not 1!
FoException Report: The menu has only 0 pages, not 1!
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.Valid.checkBoolean(Valid.java:90)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuPagged.getCurrentPageItems(MenuPagged.java:575)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuPagged.getItemAt(MenuPagged.java:498)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.compileItems(Menu.java:597)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.displayTo(Menu.java:430)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.button.ButtonMenu.onClickedInMenu(ButtonMenu.java:148)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1120)
	 at Boss-4.11.4.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor831.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
----------------------------------------------------------------------------------------------



```

**Comment by kangarko** [comment]
Thanks, will be addressed tonight.
