### ISSUE TITLE
Boss dont show the Time in Placeholder

### ISSUE THREAD

**Issue by Kuveru** [kangarko/Boss#1259]
Boss name: tatsumaru
Boss Spawning rule: tatsumaruboss

%boss_{tatsumaru}_respawn_{tatsumaruboss}%

This is the error:

[22:29:01 ERROR]: Thread DecentHolograms Thread #1 failed main thread check: getNearbyEntities
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1132) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1122) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getNearbyEntities(CraftWorld.java:1113) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.mineacademy.boss.lib.remain.Remain.getNearbyEntities(Remain.java:2676) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.model.Boss.findClosestBoss(Boss.java:2392) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.model.BossPlaceholders.onReplace(BossPlaceholders.java:82) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.lib.model.SimpleExpansion.replacePlaceholders(SimpleExpansion.java:40) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.lib.model.PlaceholderAPIHook$VariablesInjector.onRequest(HookManager.java:2765) ~[Boss-4.13.4.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
        at eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:353) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:314) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:472) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$performUpdate$6(Hologram.java:694) ~[DecentHolograms-2.8.8.jar:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.performUpdate(Hologram.java:694) ~[DecentHolograms-2.8.8.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:682) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:321) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79) ~[DecentHolograms-2.8.8.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:29:01 ERROR]: Thread DecentHolograms Thread #1 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2718) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getNMSEntities(CraftWorld.java:1098) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getEntities(CraftRegionAccessor.java:308) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.mineacademy.boss.lib.remain.Remain.getNearbyEntities(Remain.java:2681) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.model.Boss.findClosestBoss(Boss.java:2392) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.model.BossPlaceholders.onReplace(BossPlaceholders.java:82) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.lib.model.SimpleExpansion.replacePlaceholders(SimpleExpansion.java:40) ~[Boss-4.13.4.jar:?]
        at org.mineacademy.boss.lib.model.PlaceholderAPIHook$VariablesInjector.onRequest(HookManager.java:2765) ~[Boss-4.13.4.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
        at eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:353) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:314) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:472) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$performUpdate$6(Hologram.java:694) ~[DecentHolograms-2.8.8.jar:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.performUpdate(Hologram.java:694) ~[DecentHolograms-2.8.8.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:682) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:321) ~[DecentHolograms-2.8.8.jar:?]
        at eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79) ~[DecentHolograms-2.8.8.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:29:01 ERROR]: Boss 4.13.4 encountered an IllegalStateException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.20.4-R0.1-SNAPSHOT and Java 21.0.3
[22:29:01 INFO]: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[22:29:01 INFO]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[22:29:01 INFO]:        at Boss-4.13.4.jar//org.mineacademy.boss.lib.remain.Remain.getNearbyEntities(Remain.java:2681)
[22:29:01 INFO]:        at Boss-4.13.4.jar//org.mineacademy.boss.model.Boss.findClosestBoss(Boss.java:2392)
[22:29:01 INFO]:        at Boss-4.13.4.jar//org.mineacademy.boss.model.BossPlaceholders.onReplace(BossPlaceholders.java:82)
[22:29:01 INFO]:        at Boss-4.13.4.jar//org.mineacademy.boss.lib.model.SimpleExpansion.replacePlaceholders(SimpleExpansion.java:40)
[22:29:01 INFO]:        at Boss-4.13.4.jar//org.mineacademy.boss.lib.model.PlaceholderAPIHook$VariablesInjector.onRequest(HookManager.java:2765)
[22:29:01 INFO]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[22:29:01 INFO]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[22:29:01 INFO]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.utils.PAPI.setPlaceholders(PAPI.java:32)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.parsePlaceholders(HologramLine.java:353)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:314)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.update(HologramLine.java:472)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$performUpdate$6(Hologram.java:694)
[22:29:01 INFO]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.Hologram.performUpdate(Hologram.java:694)
[22:29:01 INFO]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAll(Hologram.java:682)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:321)
[22:29:01 INFO]:        at DecentHolograms-2.8.8.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[22:29:01 INFO]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[22:29:01 INFO]: [Boss] !-----------------------------------------------------!
[22:29:01 INFO]: [Boss]  Error replacing PlaceholderAPI variables
[22:29:01 INFO]: [Boss]  Identifier: {tatsumaru}_respawn_{tatsumaruboss}
[22:29:01 INFO]: [Boss]  Player: Davidlezz
[22:29:01 INFO]: [Boss] !-----------------------------------------------------!

**Comment by kangarko** [comment]
Unsupported. Your plugin calls our placeholder async while it must be called on the main thread.
