### ISSUE TITLE
Use a placeholder to know the spawn time of a boss

### ISSUE THREAD

**Issue by elhadesgamer97** [kangarko/Boss#1280]
Sorry for the ping but I have a question, do you know what or where the spawnrule is for this placeholder %boss_{bossName}respawn{spawnRule}%

**Comment by elhadesgamer97** [comment]
Yes, but what I don't understand is where or how the spawnrule is located.

**Comment by kangarko** [comment]
You can create a spawnrule in /boss menu > Spawn Rules > New > type the name in the chat, and then reference it in the variable

**Comment by elhadesgamer97** [comment]
[20:27:07 ERROR]: Boss 4.13.7 encountered an IllegalStateException! Please check your error.log and report this issue with the information in that file. Running Paper 1.21-R0.1-SNAPSHOT and Java 21.0.3
[20:27:07 INFO]: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[20:27:07 INFO]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[20:27:07 INFO]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.remain.Remain.getNearbyEntities(Remain.java:2688)
[20:27:07 INFO]:        at Boss-4.13.7.jar//org.mineacademy.boss.model.Boss.findClosestBoss(Boss.java:2392)
[20:27:07 INFO]:        at Boss-4.13.7.jar//org.mineacademy.boss.model.BossPlaceholders.onReplace(BossPlaceholders.java:82)
[20:27:07 INFO]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.model.SimpleExpansion.replacePlaceholders(SimpleExpansion.java:40)
[20:27:07 INFO]:        at Boss-4.13.7.jar//org.mineacademy.boss.lib.model.PlaceholderAPIHook$VariablesInjector.onRequest(HookManager.java:2766)
[20:27:07 INFO]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[20:27:07 INFO]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[20:27:07 INFO]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[20:27:07 INFO]:        at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.matchInception(Placeholder.java:851)
[20:27:07 INFO]:        at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:902)
[20:27:07 INFO]:        at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:821)
[20:27:07 INFO]:        at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:681)
[20:27:07 INFO]:        at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1753)
[20:27:07 INFO]:        at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$15(CMIHologram.java:2302)
[20:27:07 INFO]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:27:07 INFO]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:27:07 INFO]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[20:27:07 INFO]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[20:27:07 INFO]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[20:27:07 INFO]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[20:27:07 INFO]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[20:27:07 INFO]: [Boss] !-----------------------------------------------------!
[20:27:07 INFO]: [Boss]  Error replacing PlaceholderAPI variables
[20:27:07 INFO]: [Boss]  Identifier: pirata_respawn_spawnpirata
[20:27:07 INFO]: [Boss]  Player: hadesgamer97
[20:27:07 INFO]: [Boss] !-----------------------------------------------------!

**Comment by kangarko** [comment]
Unfortunately you can't use that placeholder in CMI or you need to make CMI render it on the main thread.

**Comment by elhadesgamer97** [comment]
Oh, that's bad. Is there any other way to set the time when the boss I created comes out?

**Comment by kangarko** [comment]
Not really, because we need to get the entity on the main thread. See if any other plugin calls PlaceholderAPI on the main thread to get the placeholder.
