### ISSUE TITLE
Error performing command /boss menu

### ISSUE THREAD

**Issue by nikeTion** [kangarko/Boss#129]
`[15:52:13] [Server thread/WARN]: java.lang.ClassCastException: me.kangarko.boss.final. .aN cannot be cast to me.kangarko.boss.final. .Z
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.final. .Z.protected(SourceFile:49)
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.final. .Z.protected(SourceFile:40)
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.final. .Z.protected(SourceFile:165)
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.final. .Z.protected(SourceFile:137)
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.command.ToolsCommand.handleSubCommand(SourceFile:21)
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.final. .COm4.handleCommand(SourceFile:172)
[15:52:13] [Server thread/WARN]: 	at me.kangarko.boss.final. .com4.onCommand(SourceFile:57)
[15:52:13] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:52:13] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[15:52:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:52:13] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:52:13] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[15:52:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[15:52:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by nikeTion** [comment]
Resolved: Restart.
