### ISSUE TITLE
1.20.6 problem with boss

### ISSUE THREAD

**Issue by ZarabiajOnline** [kangarko/Boss#1296]
Hello. I have problem with boss on 1.20.6 minecraft version.

The bosses themselves will appear, but, when I set a custom drop for them, they do not drop it after death. The next thing is that when I set the vanilla drop not to fall out, this change of this option does not work.
Please help.

I have included the report below.

Boss 4.13.1 encountered an InvocationTargetException
Running Purpur 1.20.6-R0.1-SNAPSHOT and Java 21.0.3
Plugins: ViaVersion v5.0.3, LuckPerms v5.4.137, Vault v1.7.3-b131, WildStacker v2024.2, PlaceholderAPI v2.11.6, WorldEdit v7.3.5+6880-8ba3d89, SuperiorSkyblock2 v2024.2-b300, ProtocolLib v5.3.0-SNAPSHOT-726, HeadDatabase v4.19.8, WorldGuard v7.0.10+d9424b1, Multiverse-Core v4.3.1-b861, DecentHolograms v2.8.10, NBTAPI v2.13.2, SCore v5.24.8.13, LoneLibs v1.0.58, Essentials v2.21.0-dev+111-b54c8c1, Skript v2.9.1, Vulcan v2.9.0, Citizens v2.0.35-SNAPSHOT (build 3494), ExecutableItems v7.24.8.13, ItemsAdder v4.0.1-alpha-test-5, Boss v4.13.1, ViaBackwards v5.0.3, Dungeons v3.4.7, SkinsRestorer v15.4.2, packetevents v2.4.0, nightcore v2.6.3, SpawnerMeta v24.4, EssentialsChat v2.21.0-dev+111-b54c8c1, spark v1.10.105, WorldGuardExtraFlags v4.2.4-SNAPSHOT, DeluxeMenus v1.14.0-Release, TradeSystem v2.6.0, DailyRewardsPlus v1.4.0, InventoryRollbackPlus v1.6.17, AxAuctions v1.12.5, PistonMOTD v5.1.1, ajLeaderboards v2.9.0, SupremeTags v2.0.3, ExcellentCrates v5.3.2, AntiPopup v9.2, Shopkeepers v2.22.3, LobbyGames v1.6.3, AutoMessage v5.1.4, Roulette v2.1, UltimateAutoRestart v2024.07, TAB v4.1.6, VoidTeleport v2.4.5, UltimateAntiBot v4.1.2-ABYSS, VillagerOverhaul v1.1.4, Authy v3.5.2, EconomyShopGUI v6.7.10, EssentialsSpawn v2.21.0-dev+111-b54c8c1, ToastedAFK v2.6.3.5, Vouchers v3.24.0, InvSeePlusPlus v0.29.4, PL-Hide v1.5.22, PlayerKits2 v1.12.2
----------------------------------------------------------------------------------------------

More Information: 
Could not make new instance of public org.mineacademy.boss.listener.EntityListener() with params: 
InvocationTargetException (Unknown cause)
	 at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.ReflectionUtil.instantiate(ReflectionUtil.java:583)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.AutoRegisterScanner.findInstance(AutoRegisterScanner.java:443)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.AutoRegisterScanner.autoRegister(AutoRegisterScanner.java:283)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:121)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:300)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
NoClassDefFoundError org/spigotmc/event/entity/EntityDismountEvent (wrong name: org/bukkit/event/entity/EntityDismountEvent)
	 at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	 at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	 at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243)
	 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144)
	 at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43)
	 at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37)
	 at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187)
	 at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
	 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	 at java.base/java.lang.Class.forName0(Native Method)
	 at java.base/java.lang.Class.forName(Class.java:534)
	 at java.base/java.lang.Class.forName(Class.java:513)
	 at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
	 at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
	 at Boss-4.13.1.jar//org.mineacademy.boss.listener.EntityListener.<init>(EntityListener.java:112)
	 at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.ReflectionUtil.instantiate(ReflectionUtil.java:583)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.AutoRegisterScanner.findInstance(AutoRegisterScanner.java:443)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.AutoRegisterScanner.autoRegister(AutoRegisterScanner.java:283)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:121)
	 at Boss-4.13.1.jar//org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:300)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
	 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
	 at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)

**Comment by kangarko** [comment]
Thanks, going to be fixed in a few days in Boss 5.
