### ISSUE TITLE
Problem with citizen and boss plugin

### ISSUE THREAD

**Issue by SuperGamer1809** [kangarko/Boss#1302]
`[16:09:59 WARN]: [Boss] Plugin Boss v5.0.0 generated an exception while executing task 8596
java.lang.AbstractMethodError: Receiver class org.mineacademy.boss.lib.debug.Debugger$$Lambda/0x00007ff6b5600850 does not define or inherit an implementation of the resolved method 'abstract io.sentry.SentryEvent execute(io.sentry.SentryEvent, java.lang.Object)' of interface io.sentry.SentryOptions$BeforeSendCallback.
        at io.sentry.SentryClient.executeBeforeSend(SentryClient.java:553) ~[sentry-5.4.0.jar:?]
        at io.sentry.SentryClient.captureEvent(SentryClient.java:118) ~[sentry-5.4.0.jar:?]
        at io.sentry.Hub.captureException(Hub.java:169) ~[sentry-5.4.0.jar:?]
        at io.sentry.IHub.captureException(IHub.java:99) ~[sentry-5.4.0.jar:?]
        at io.sentry.Sentry.captureException(Sentry.java:294) ~[sentry-5.4.0.jar:?]
        at Boss-5.0.0.jar/org.mineacademy.boss.lib.debug.Debugger.lambda$saveError$2(Debugger.java:111) ~[Boss-5.0.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by kangarko** [comment]
Try the next version please, avoid using plugman or reloading to install it. Restart cleanly.
