### ISSUE TITLE
1.8.8: Plugin don't start

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1306]
PandaSpigot-1.8.8 (Paper's fork) and Java 17

The plugin doesn't start in the leatest version, here's the startup error:

```
[12:31:35 INFO]: [Boss] Enabling Boss v5.0.2
[12:31:35 INFO]: [Boss]  ___   ___   __   __  
[12:31:35 INFO]: [Boss] | |_) / / \ ( (` ( (` 
[12:31:35 INFO]: [Boss] |_|_) \_\_/ _)_) _)_) 
[12:31:35 INFO]:   
[12:31:35 INFO]: [PlaceholderAPI] Successfully registered internal expansion: boss [5.0.2]
[12:31:35 INFO]: [Boss] Updating settings.yml at 'Sentry' -> 'true'
[12:31:35 INFO]: [Boss] Updating settings.yml at 'Spawning.Count_Unloaded_Bosses_In_Limits' -> 'true'
[12:31:35 INFO]: [Boss] Updating settings.yml at 'Spawning.Live_Updates' -> 'true'
[12:31:35 INFO]: [Boss] Warning: Counting unloaded Bosses requires a modern Paper software. Disabling...
[12:31:35 INFO]: [Boss] Warning: The following entries in settings.yml are unused and were moved to plugins/Boss/unused/settings.yml: [Spawning.World_Limit, Spawning.Count_Unloaded_Bosses, Date_Format, Date_Format_Short, Date_Format_Month, Location_Format, Version]
[12:31:35 INFO]: java.lang.NoSuchMethodError: 'java.util.Set com.google.gson.JsonObject.keySet()'
[12:31:35 INFO]:        at org.mineacademy.boss.lib.settings.Lang$Storage.putToDictionary(Lang.java:641)
[12:31:35 INFO]:        at org.mineacademy.boss.lib.settings.Lang$Storage.load(Lang.java:534)
[12:31:35 INFO]:        at org.mineacademy.boss.lib.platform.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:231)
[12:31:35 INFO]:        at org.mineacademy.boss.lib.platform.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:93)
[12:31:35 INFO]:        at org.mineacademy.boss.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:374)
[12:31:35 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[12:31:35 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[12:31:35 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454)
[12:31:35 INFO]: [Boss]     ___                  _ 
[12:31:35 INFO]: [Boss]    / _ \  ___  _ __  ___| |
[12:31:35 INFO]: [Boss]   | | | |/ _ \| '_ \/ __| |
[12:31:35 INFO]: [Boss]   | |_| | (_) | |_) \__ \_|
[12:31:35 INFO]: [Boss]    \___/ \___/| .__/|___(_)
[12:31:35 INFO]: [Boss]              |_|          
[12:31:35 INFO]: [Boss] !-----------------------------------------------------!
[12:31:35 INFO]: [Boss]  Error loading Boss v5.0.2, plugin is disabled!
[12:31:35 INFO]: [Boss]  Running on PandaSpigot 1.8.8-R0.1-SNAPSHOT & Java 17.0.11
[12:31:35 INFO]: [Boss] !-----------------------------------------------------!
[12:31:35 INFO]: [Boss]  Error: 'java.util.Set com.google.gson.JsonObject.keySet()'
[12:31:35 INFO]: [Boss] !-----------------------------------------------------!
[12:31:35 INFO]: [Boss] Disabling Boss v5.0.2
```

**Comment by kangarko** [comment]
Can you please send me the entire startup log?
