### ISSUE TITLE
Minecraft Version: 1.20.1 : Getting console spam

### ISSUE THREAD

**Issue by ProjectGuinness** [kangarko/Boss#1309]
Hello,

Minecraft version above, getting this error spammed in my console 

Also what's causing this spam? 

[21:21:45] [Server thread/ERROR]: Could not pass event EntityRemoveFromWorldEvent to Boss v5.0.3
java.lang.NoSuchMethodError: 'org.bukkit.World com.destroystokyo.paper.event.entity.EntityRemoveFromWorldEvent.getWorld()'
    at org.mineacademy.boss.listener.CompPaperRemoveEntityEvent.onChunkUnload(ChunkListener.java:290) ~[Boss-5.0.3.jar:?]
    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2847) ~[?:?]
    at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2694) ~[?:?]
    at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:295) ~[paper-1.20.2.jar:git-Paper-318]
    at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:886) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4750) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.world.entity.Entity.remove(Entity.java:699) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:759) ~[?:?]
    at net.minecraft.world.entity.Entity.discard(Entity.java:681) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.world.entity.Mob.checkDespawn(Mob.java:884) ~[?:?]
    at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:886) ~[?:?]
    at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
    at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ProjectGuinness** [comment]
Corre

**Comment by ProjectGuinness** [comment]
Seems to be causing crashes when editing the mobs
