### ISSUE TITLE
1.8.9 - Can't use playervaultsx?

### ISSUE THREAD

**Issue by HawkDevelopment** [kangarko/Boss#1327]
Can't use playervaultsx with boss?

[15:53:04] [Server thread/ERROR]: Error occurred while enabling Boss v5.0.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.mineacademy.boss.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:244) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:380) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:321) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:485) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:449) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:404) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:687) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
Caused by: java.lang.NullPointerException: Foundation instance not set yet.
	at org.mineacademy.boss.lib.platform.Platform.getPlatform(Platform.java:38) ~[?:?]
	at org.mineacademy.boss.lib.platform.Platform.getPlatformVersion(Platform.java:109) ~[?:?]
	at org.mineacademy.boss.lib.MinecraftVersion.<clinit>(MinecraftVersion.java:155) ~[?:?]
	... 12 more
[15:53:04] [Server thread/INFO]: [Boss] Disabling Boss v5.0.6
[15:53:04] [Server thread/ERROR]: Error occurred while disabling Boss v5.0.6 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.boss.lib.CommonCore
	at org.mineacademy.boss.lib.platform.SimplePlugin.onDisable(SimplePlugin.java:552) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:354) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:380) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:321) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:485) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:449) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:404) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:687) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
	
	
[15:53:04] [Server thread/INFO]: [PlayerVaults] Enabling PlayerVaults v4.2.14
[15:53:04] [Server thread/ERROR]: Error occurred while enabling PlayerVaults v4.2.14 (Is it up to date?)
java.lang.IllegalAccessError: tried to access class net.kyori.adventure.key.KeyImpl from class net.kyori.adventure.key.Key
	at net.kyori.adventure.key.Key.key(Key.java:137) ~[?:?]
	at net.kyori.adventure.translation.GlobalTranslatorImpl.<clinit>(GlobalTranslatorImpl.java:41) ~[?:?]
	at net.kyori.adventure.translation.GlobalTranslator.renderer(GlobalTranslator.java:75) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.<init>(BukkitAudiencesImpl.java:156) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.builder(BukkitAudiencesImpl.java:85) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
	at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
	at com.drtshock.playervaults.PlayerVaults.onEnable(PlayerVaults.java:137) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:380) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:321) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:485) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:449) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:404) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:687) [WineSpigot-V1.9.17-old.jar:1_8_R3]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
    
    
    Works without PlayerVaultsX installed, kind of need it tho.

**Comment by HawkDevelopment** [comment]
Tried with latest version down to 5.0.6

**Comment by kangarko** [comment]
Please post me your /boss debug as well as the full startup log. 

Looks like the other plugin and we are shading the same dependency and somehow there is a conflict, I will investigate asap I just need to know your environment.

**Comment by kangarko** [comment]
The plugin no longer supports 1.8.8, which version of it are you using? Please send me the jar, it should be fine since it's open source on github anyways.

**Comment by kangarko** [comment]
I got playervaultx working for 1.8.8 but I cannot reproduce, please post me the latest stack trace for Boss 5.0.10

**Comment by HawkDevelopment** [comment]
Will do right now

**Comment by HawkDevelopment** [comment]
[15:18:10 INFO]: [Boss] Enabling Boss v5.0.10
[15:18:10 INFO]: [Boss]  ___   ___   __   __
[15:18:10 INFO]: [Boss] | |_) / / \ ( (` ( (`
[15:18:10 INFO]: [Boss] |_|_) \_\_/ _)_) _)_)
[15:18:10 INFO]:
[15:18:10 INFO]: [PlaceholderAPI] Successfully registered internal expansion: boss [5.0.10]
[15:18:10 INFO]: [Boss] *---------------------------------------------------*
[15:18:10 INFO]: [Boss]  Error parsing mini message tags in: Boss //
[15:18:10 INFO]: [Boss] *---------------------------------------------------*
[15:18:10 WARN]: java.lang.IllegalAccessError: tried to access class net.kyori.adventure.text.TextComponentImpl from class net.kyori.adventure.text.Component
[15:18:10 WARN]:        at net.kyori.adventure.text.Component.empty(Component.java:137)
[15:18:10 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessageParser.treeToComponent(MiniMessageParser.java:214)
[15:18:10 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:210)
[15:18:10 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:79)
[15:18:10 WARN]:        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:45)
[15:18:10 WARN]:        at org.mineacademy.boss.lib.model.SimpleComponent.fromMini(SimpleComponent.java:722)
[15:18:10 WARN]:        at org.mineacademy.boss.lib.settings.SimpleSettings.<clinit>(SimpleSettings.java:62)
[15:18:10 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:18:10 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:18:10 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:18:10 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:18:10 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[15:18:10 WARN]:        at org.mineacademy.boss.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:60)
[15:18:10 WARN]:        at org.mineacademy.boss.lib.platform.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:224)
[15:18:10 WARN]:        at org.mineacademy.boss.lib.platform.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:93)
[15:18:10 WARN]:        at org.mineacademy.boss.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:393)
[15:18:10 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:18:10 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[15:18:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464)
[15:18:10 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:380)
[15:18:10 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:321)
[15:18:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:485)
[15:18:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:449)
[15:18:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:404)
[15:18:10 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268)
[15:18:10 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:687)
[15:18:10 WARN]:        at java.lang.Thread.run(Thread.java:750)
[15:18:10 INFO]: java.lang.UnsupportedOperationException: HandledException do not support getMessage()
[15:18:10 INFO]:        at org.mineacademy.boss.lib.exception.HandledException.getMessage(HandledException.java:16)
[15:18:10 INFO]:        at org.mineacademy.boss.lib.CommonCore.replaceErrorVariable(CommonCore.java:474)
[15:18:10 INFO]:        at org.mineacademy.boss.lib.CommonCore.throwError(CommonCore.java:458)
[15:18:10 INFO]:        at org.mineacademy.boss.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:72)
[15:18:10 INFO]:        at org.mineacademy.boss.lib.platform.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:224)
[15:18:10 INFO]:        at org.mineacademy.boss.lib.platform.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:93)
[15:18:10 INFO]:        at org.mineacademy.boss.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:393)
[15:18:10 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:18:10 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[15:18:10 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464)
[15:18:10 INFO]: [Boss]     ___                  _
[15:18:10 INFO]: [Boss]    / _ \  ___  _ __  ___| |
[15:18:10 INFO]: [Boss]   | | | |/ _ \| '_ \/ __| |
[15:18:10 INFO]: [Boss]   | |_| | (_) | |_) \__ \_|
[15:18:10 INFO]: [Boss]    \___/ \___/| .__/|___(_)
[15:18:10 INFO]: [Boss]              |_|
[15:18:10 INFO]: [Boss] !-----------------------------------------------------!
[15:18:10 INFO]: [Boss]  Error loading Boss v5.0.10, plugin is disabled!
[15:18:10 INFO]: [Boss]  Running on WineSpigot 1.8.8-R0.2-SNAPSHOT & Java 1.8.0_402
[15:18:10 INFO]: [Boss] !-----------------------------------------------------!
[15:18:10 INFO]: [Boss]  Unable to setup reflection!
[15:18:10 INFO]: [Boss]  Your server is either too old or
[15:18:10 INFO]: [Boss]  the plugin broke on the new version :(
[15:18:10 INFO]: [Boss]  Error: HandledException do not support getMessage()
[15:18:10 INFO]: [Boss] !-----------------------------------------------------!
[15:18:10 INFO]: [Boss] Disabling Boss v5.0.10
[15:18:10 INFO]: [Boss] Plugin might not shut down property. Got NullPointerException: null
[15:18:10 ERROR]: Error occurred while disabling Boss v5.0.10 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.boss.settings.Settings
        at org.mineacademy.boss.BossPlugin.areRegionsEnabled(BossPlugin.java:214) ~[?:?]
        at org.mineacademy.boss.lib.platform.SimplePlugin.onDisable(SimplePlugin.java:745) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:354) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.mineacademy.boss.lib.platform.SimplePlugin.displayError(SimplePlugin.java:704) [Boss-5.0.10.jar:?]
        at org.mineacademy.boss.lib.platform.SimplePlugin.onEnable(SimplePlugin.java:454) [Boss-5.0.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:380) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:321) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:485) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:449) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:404) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:687) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
[15:18:10 INFO]: [PlayerVaults] Enabling PlayerVaults v4.2.14
[15:18:10 ERROR]: Error occurred while enabling PlayerVaults v4.2.14 (Is it up to date?)
java.lang.IllegalAccessError: tried to access class net.kyori.adventure.key.KeyImpl from class net.kyori.adventure.key.Key
        at net.kyori.adventure.key.Key.key(Key.java:137) ~[?:?]
        at net.kyori.adventure.translation.GlobalTranslatorImpl.<clinit>(GlobalTranslatorImpl.java:41) ~[?:?]
        at net.kyori.adventure.translation.GlobalTranslator.renderer(GlobalTranslator.java:75) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.<init>(BukkitAudiencesImpl.java:156) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.builder(BukkitAudiencesImpl.java:85) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        at com.drtshock.playervaults.PlayerVaults.onEnable(PlayerVaults.java:137) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:464) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:380) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:321) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:485) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:449) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:404) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:268) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:687) [WineSpigot-V1.9.17-old.jar:1_8_R3]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
[15:18:10 INFO]: [PlayerVaults] Disabling PlayerVaults v4.2.14

**Comment by kangarko** [comment]
I'm sorry, but I can't find your /boss debug and the above is not a full startup log (upload it to pastebin.com please)

**Comment by kangarko** [comment]
What fixed it? I could never reproduce I even compiled the old playervaults:

![a](https://i.imgur.com/k0a9TSp.png)

**Comment by kangarko** [comment]
@HawkDevelopment

**Comment by HawkDevelopment** [comment]
Ngl I'm not sure. It just started working XD

**Comment by kangarko** [comment]
Okay great to know!
