### ISSUE TITLE
1.8.8: Names Bug & Spawn Critical Error

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1338]
Using pandaspigot-130 and 5.1.1 Boss Version

The first bug it's when you restart the server the bosses don't dissappers with /boss butcher even with "Count_Unloaded_Bosses_In_Limits" enabled. (We already have the same bug before https://github.com/kangarko/Boss/issues/1240)

For reproduce:
You have only to spawn some bosses, unload the chunk (idk if it's necessarly) and restart the server, when start you try to use /boss butcher *.

---

The second it's about the name console flood. It's when your boss have **"** in the name like:
![image](https://github.com/user-attachments/assets/e91f535f-3710-4066-9361-f02c37a0e004)

We have this error in console always when you hit this boss:
```
[03:17:09 INFO]: [Boss] *---------------------------------------------------*
[03:17:09 INFO]: [Boss]  Failed to execute event for entity CraftSkeleton
[03:17:09 INFO]: [Boss]  Error: MalformedJsonException: Unterminated object at line 1 column 50 path $.text
[03:17:09 INFO]: [Boss] *---------------------------------------------------*
[03:17:09 INFO]: org.mineacademy.boss.lib.exception.ReflectionException: Could not invoke method public static net.minecraft.server.v1_8_R3.IChatBaseComponent net.minecraft.server.v1_8_R3.IChatBaseComponent$ChatSerializer.a(java.lang.String) on instance null with params {"text":"- 0.46 ⚔ | I.A. Suporte "Ômega" - [888 / 888]"}
[03:17:09 INFO]:        at org.mineacademy.boss.lib.ReflectionUtil.invoke(ReflectionUtil.java:401)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.remain.Remain.convertJsonToIChatBase(Remain.java:809)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.remain.Remain.convertLegacyToIChatBase(Remain.java:797)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.remain.Remain.sendActionBarLegacyPacket(Remain.java:2226)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.platform.BukkitPlayer.sendActionBar(BukkitPlayer.java:111)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.HealthBarUtil.display(HealthBarUtil.java:71)
[03:17:09 INFO]:        at org.mineacademy.boss.listener.EntityListener.lambda$onDamage$6(EntityListener.java:544)
[03:17:09 INFO]:        at org.mineacademy.boss.listener.BossListener.runIfBoss(BossListener.java:30)
[03:17:09 INFO]:        at org.mineacademy.boss.listener.EntityListener.onDamage(EntityListener.java:532)
[03:17:09 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[03:17:09 INFO]: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 50 path $.text
[03:17:09 INFO]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
[03:17:09 INFO]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:495)
[03:17:09 INFO]:        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
[03:17:09 INFO]:        at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666)
[03:17:09 INFO]:        at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
[03:17:09 INFO]:        at com.google.gson.internal.Streams.parse(Streams.java:44)
[03:17:09 INFO]:        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
[03:17:09 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:810)
[03:17:09 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:775)
[03:17:09 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:724)
[03:17:09 INFO]:        at com.google.gson.Gson.fromJson(Gson.java:696)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.ReflectionUtil.invoke(ReflectionUtil.java:398)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.remain.Remain.convertJsonToIChatBase(Remain.java:809)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.remain.Remain.convertLegacyToIChatBase(Remain.java:797)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.remain.Remain.sendActionBarLegacyPacket(Remain.java:2226)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.platform.BukkitPlayer.sendActionBar(BukkitPlayer.java:111)
[03:17:09 INFO]:        at org.mineacademy.boss.lib.HealthBarUtil.display(HealthBarUtil.java:71)
[03:17:09 INFO]:        at org.mineacademy.boss.listener.EntityListener.lambda$onDamage$6(EntityListener.java:544)
[03:17:09 INFO]:        at org.mineacademy.boss.listener.BossListener.runIfBoss(BossListener.java:30)
[03:17:09 INFO]:        at org.mineacademy.boss.listener.EntityListener.onDamage(EntityListener.java:532)
[03:17:09 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
```

---

The third bug it's again about the names, when your boss have bold (&l) format, for some reason all the name stays bold too. Here's some demonstration:

![image](https://github.com/user-attachments/assets/63769f97-9429-4d54-a779-3020ddf2ddd4)
![image](https://github.com/user-attachments/assets/cabdf0c8-6d33-4ba5-b178-ba0406bdf541)
![image](https://github.com/user-attachments/assets/5c119e83-9cdb-4b64-998d-f77bb316656f)

**Comment by kangarko** [comment]
I fixed it! Please use the &r letter before the new color to get rid of the bold:

![a](https://i.imgur.com/LBk0RuU.png)

**Comment by kangarko** [comment]
Unfortunately 1.8.8 does not implement all the necessary API events to allow Count_Unloaded_Bosses_In_Limits work consistently. A new Paper version is required. You can still remove unloaded Bosses with /boss scan

**Comment by kangarko** [comment]
I apologize, I was sick and still recovering, I'll be dealing with this on Saturday/Sunday, please downgrade for now.

**Comment by kangarko** [comment]
Got better thanks! Will be releasing the update tonight.

**Comment by kangarko** [comment]
Thanks for the recording.

It really looks like a third party plugin is causing an incompatibility, because I cannot reproduce this on stock Paper 1.8.8. I suggest you make a copy of your server with just Boss installed and then drop plugins one by one to find the one that's causing it, and let me know maybe I can fix it.

**Comment by kangarko** [comment]
Thanks, apology for the slow support on this one. No need to ping because I get all notifications in the feed and process from the oldest

**Comment by kangarko** [comment]
@IceGames23 https://www.loom.com/share/529490f88ed04f7c8c4558261e21cdac

**Comment by kangarko** [comment]
If the tool says that the entity is not a boss you can still dump its NBT tag to the console, please dump the Boss' tag right after you spawn it, and also when it breaks, and paste both to me please.

**Comment by kangarko** [comment]
To get the NBT dump just type /boss tools then get the info stick and right/left click an entity. Then click the chat message to dump the NBT to the console.

**Comment by kangarko** [comment]
Sorry I cant read this. Please use the service above to format it. I need two, not one dumps.

1. Dump from the Boss when it is working
2. Dump from the Boss when it stops working.

Thanks!

**Comment by kangarko** [comment]
Thank you. There is nothing strange in the files unfortunately. Can you try setting Count_Unloaded_Bosses_In_Limits from false to true in settings.yml? 

Also, when you fly away from loaded bosses and they become unloaded, can you please tell me if their UUIDs appear in either metadata.yml or unloaded-bosses.yml files?

Many, many thanks for your patience!

**Comment by kangarko** [comment]
Got it, what is your builtbybit username please?

**Comment by kangarko** [comment]
Thanks, I have contacted BuiltByBit to give you a full refund, because we have spent two weeks on this and I cannot reproduce nor find the problem , I understand it's frustrating and I unfortunately was not able to provide the help at the quality I wanted. We did not receive any other reports regarding this which makes me believe it's something in your server or plugin setup. I am very sorry. You can keep the plugin as an apology.

**Comment by kangarko** [comment]
Sure. Given back. However I am really not able to reproduce nor fix this at the moment.

**Comment by kangarko** [comment]
Got it, thanks, I will have a look when I have time. Can you please test on stock Paper from papermc.io build of 1.8.8 and confirm it is happening there too?

**Comment by kangarko** [comment]
Thanks for confirming, I'll have a look after I finish ChatControl v11, these days are crazy busy :/

**Comment by kangarko** [comment]
Please re-test on the next version. If it still happens, please let me know which plugins are installed.

**Comment by kangarko** [comment]
The plugin is doing some relocations which cause classpath conflict. They need to relocate the Adventure library into an isolated package:

![a](https://i.imgur.com/YH0tEDk.png)

Please read this article from my other plugin to understand this issue. This is something the other developer needs to fix:

https://github.com/kangarko/chatcontrol-red/wiki/JAR-hell

**Comment by kangarko** [comment]
Which one? The relocations? Yes.

**Comment by kangarko** [comment]
Thank you, finally fixed!!!

**Comment by kangarko** [comment]
An internal check removing invalid UUIDs not taking into account yet unloaded entities, I simply removed that check.
