### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by Xpomodz** [kangarko/Boss#1350]
Happens when i edit a config or delete a config, also boss doesnt go away when config is deleted.

```

[19:07:38 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.remain.Remain.runTaskTimer(Remain.java:2933)
[19:07:38 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlatform.runTaskTimer(BukkitPlatform.java:661)
[19:07:38 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.FoundationPlatform.runTaskTimer(FoundationPlatform.java:178)
[19:07:38 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.Platform.runTaskTimer(Platform.java:362)
[19:07:38 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.BossPlugin.onPluginStart(BossPlugin.java:136)
[19:07:38 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:376)
[19:07:38 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:07:38 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:07:39 INFO]: java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.skills" is null
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.model.Boss.getSkills(Boss.java:1758)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:120)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.run(TaskBehavior.java:99)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore$1.run(CommonCore.java:1787)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1780)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.remain.Remain.runTaskTimer(Remain.java:2933)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlatform.runTaskTimer(BukkitPlatform.java:661)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.FoundationPlatform.runTaskTimer(FoundationPlatform.java:178)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.Platform.runTaskTimer(Platform.java:362)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.BossPlugin.onPluginStart(BossPlugin.java:136)
[19:07:39 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:376)
[19:07:39 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:07:39 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:07:40 INFO]: java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.skills" is null
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.model.Boss.getSkills(Boss.java:1758)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:120)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.run(TaskBehavior.java:99)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore$1.run(CommonCore.java:1787)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1780)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.remain.Remain.runTaskTimer(Remain.java:2933)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlatform.runTaskTimer(BukkitPlatform.java:661)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.FoundationPlatform.runTaskTimer(FoundationPlatform.java:178)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.Platform.runTaskTimer(Platform.java:362)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.BossPlugin.onPluginStart(BossPlugin.java:136)
[19:07:40 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:376)
[19:07:40 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:07:40 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:07:41 INFO]: java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.skills" is null
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.model.Boss.getSkills(Boss.java:1758)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:120)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.run(TaskBehavior.java:99)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore$1.run(CommonCore.java:1787)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1780)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.remain.Remain.runTaskTimer(Remain.java:2933)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlatform.runTaskTimer(BukkitPlatform.java:661)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.FoundationPlatform.runTaskTimer(FoundationPlatform.java:178)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.Platform.runTaskTimer(Platform.java:362)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.BossPlugin.onPluginStart(BossPlugin.java:136)
[19:07:41 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:376)
[19:07:41 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:07:41 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:07:42 INFO]: java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.skills" is null
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.model.Boss.getSkills(Boss.java:1758)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:120)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.run(TaskBehavior.java:99)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore$1.run(CommonCore.java:1787)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1780)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.remain.Remain.runTaskTimer(Remain.java:2933)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlatform.runTaskTimer(BukkitPlatform.java:661)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.FoundationPlatform.runTaskTimer(FoundationPlatform.java:178)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.Platform.runTaskTimer(Platform.java:362)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.BossPlugin.onPluginStart(BossPlugin.java:136)
[19:07:42 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:376)
[19:07:42 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:07:42 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:07:43 INFO]: java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.skills" is null
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.model.Boss.getSkills(Boss.java:1758)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.skill(TaskBehavior.java:120)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.task.TaskBehavior.run(TaskBehavior.java:99)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore$1.run(CommonCore.java:1787)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.CommonCore.wrapRunnableInExceptionCatcher(CommonCore.java:1780)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.remain.Remain.runTaskTimer(Remain.java:2933)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlatform.runTaskTimer(BukkitPlatform.java:661)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.FoundationPlatform.runTaskTimer(FoundationPlatform.java:178)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.Platform.runTaskTimer(Platform.java:362)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.BossPlugin.onPluginStart(BossPlugin.java:136)
[19:07:43 INFO]:        at Boss-5.2.2.jar//org.mineacademy.boss.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:376)
[19:07:43 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:07:43 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
```

**Comment by Xpomodz** [comment]
[19:11:16 INFO]: [Boss] Plugin might not shut down property. Got NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "this.potionEffects" is null

**Comment by kangarko** [comment]
apology, looks like my other commit had caused this: https://github.com/kangarko/Foundation/commit/07bdcf6e5f56111ebf44ea16464d6a8fdb4e8f2b. I now solved this issue and will ship a patch in the next version to reverse the wrong save.
