### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yotam1802** [kangarko/Boss#149]
I get an error when starting the server. 

[00:28:21 INFO]: [Boss] Enabling Boss v1.7.3
[00:28:21 ERROR]: Error occurred while enabling Boss v1.7.3 (Is it up to date?)
java.lang.BootstrapMethodError: call site initialization exception
        at java.lang.invoke.CallSite.makeSite(Unknown Source) ~[?:?]
        at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source) ~[?:?]
        at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source) ~[?:?]
        at me.kangarko.boss.final. .Lpt5.onEnable(SourceFile:107) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException
        at me.kangarko.boss.final. .Lpt5.?????????(SourceFile) ~[?:?]
        ... 15 more

**Comment by kangarko** [comment]
That's the weirdest error I seen in a while; are you using Spigot , PaperSpigot or any other?

Also, please update to the latest version of Boss.
