### ISSUE TITLE
Help me pls. Im Thai.

### ISSUE THREAD

**Issue by snowva123** [kangarko/Boss#152]
I cant use Skill menu.
------------------------------------[ 08.08.2018 07:11:53 ]-----------------------------------
Boss 1.7.4 encountered a COm9
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 10.0.2
Plugins: LetterHeads v18.2, SupplySign v1.9.9b, GroupManager v2.0.1-b332, Boss v1.7.4, BlockedCommands v1.0, NametagEdit v4.2.0, Broadcaster v2.1.0, Lockette v1.8.21, MultiWorld v5.2.7, Arconix v2.0.0, SkinsRestorer v13.3, MobHealth v10.0.1, BanItem v2.8, ViaVersion v1.4.1, Itemizer v3.4, WorldEdit v6.1;no_git_id, ArcaneEnchants v5.2.4, OpenInv v3.1.2, ClearLag v2.9.7, ColorMOTD v1.3, WorldBorder v1.8.6, ProtocolLib v3.6.4, AutoSaveWorld v4.15, NoCheatPlus v3.16.0-RC-sMD5NET-b1134, Vault v1.5.6-b49, BloodInMinecraft v2, MassiveCore v2.14.0, BConomy v1.7, CreativeGates v2.14.0, Trading v3.2, HolographicDisplays v2.2.6, Marriage v2.0.18, WorldGuard v6.1.3-SNAPSHOT;c904242, RepairPlus v1.4.0, RedstoneClockPreventer v1.3.1, Essentials v2.15.0.1, SignChestShop v1.4, Citizens v2.0.16-SNAPSHOT (build 1267), Shopkeepers v1.68, EssentialsChat v2.15.0.1, ProtectionStones v1.9j, EssentialsProtect v2.15.0.1, ServerSigns v4.5.1, EssentialsSpawn v2.15.0.1, WorldGuardExtraFlags v3.0.4, TitleManager v2.0.10, AuthMe v5.4.0-b1877, Factions v1.6.9.5-U0.2.2-b116, LeaderHeads v3.1.8.3, PlayMoreSounds v2.4.0, McDuels v15.0.0, MyPet v2.3.4
----------------------------------------------------------------------------------------------

More Information: 
Material == null!
COm9 Report / Material == null!
	 at me.kangarko.boss.final. .Com2.protected(SourceFile:20)
	 at me.kangarko.boss.final. .X.short(SourceFile:89)
	 at me.kangarko.boss.final. .bq.getIcon(SourceFile:82)
	 at me.kangarko.boss.final. .aJ$NuL.protected(SourceFile:1296)
	 at me.kangarko.boss.final. .aJ$NuL.protected(SourceFile:1288)
	 at me.kangarko.boss.final. .ai.protected(SourceFile:123)
	 at me.kangarko.boss.final. .Y.protected(SourceFile:153)
	 at me.kangarko.boss.final. .Y.protected(SourceFile:137)
	 at me.kangarko.boss.final. .Z$aUx.protected(SourceFile:171)
	 at me.kangarko.boss.final. .Y.protected(SourceFile:262)
	 at me.kangarko.boss.final. .ab.onInvClick(SourceFile:61)
	 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thank you, fixed.
