### ISSUE TITLE
Region Spawning

### ISSUE THREAD

**Issue by StoopidMeap** [kangarko/Boss#165]
For the gui item on region spawning, it says it is disabled. Is there a way to enable this? When I click it, it shows this error (Sorry if this is the wrong place):

[09:35:40] [Server thread/INFO]: ^[[0;30;1m^[[21mBOSS ^[[0;30;1m//^[[0;37;22m ^[[0;31;1mError clicking in menu prn{}^[[m
[09:35:40] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .LPt4.protected(SourceFile:1421)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .LPT1.lpt5(SourceFile:597)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .aZ.protected(SourceFile:18)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.api.model.BossRegionType.getRegions(SourceFile:78)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .aK$coN.protected(SourceFile:1920)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .aK$coN.protected(SourceFile:1869)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .aj.protected(SourceFile:123)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .aK$coN.protected(SourceFile:1953)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .Z.protected(SourceFile:153)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .Z.protected(SourceFile:137)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .aa$aUx.protected(SourceFile:171)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .Z.protected(SourceFile:262)
[09:35:40] [Server thread/WARN]:        at me.kangarko.boss.final. .ac.onInvClick(SourceFile:61)
[09:35:40] [Server thread/WARN]:        at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
[09:35:40] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:35:40] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[09:35:40] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[09:35:40] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:35:40] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[09:35:40] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2140)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[09:35:40] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:35:40] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[09:35:40] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[09:35:40] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by kangarko** [comment]
Make sure you use the very latest WorldGuard version from builds.enginehub.org
