### ISSUE TITLE
boss region error after delete the map

### ISSUE THREAD

**Issue by SeanWalk** [kangarko/Boss#233]
i delete the map which already set up some region for BOSS
now it output some error when startup.
but i can remove those region from command.

every region send a error message like this
`
------------------------------------[ 23.01.2019 21:31:17 ]-----------------------------------
Boss 1.8.17 encountered a CoM9
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_201
Plugins: CoreProtect v2.15.2, LuckPerms v4.3.73, Wild v3.14.14, WorldEdit v7.0.0-SNAPSHOT;3997-ba8bde0, AntiCreeper v1.7, ShearedChickens v0.01, NBTEditor v3.1, PlaceholderAPI v2.9.2-DEV-59, Lift v${version}, PacketListenerApi v3.7.1-SNAPSHOT, Boss v1.8.17, WorldBorder v1.9.0, MapManager v1.7.0-SNAPSHOT, The Multiverse-Core Plugin, ProtocolLib v4.4.0, ChestLockGui v1.0.9, ColdStorage v1.1.1, PocketGames v3.7.7, BlocksHub v3.0.0, ActionAnnouncer v1.13.1, Vault v1.7.1-b91, FurnaceLevels v1.3, LightAPI v3.2.9, AnimatedFrames v4.11.1-SNAPSHOT, PerWorldInventory v2.2.2, QuickShop vReremake 1.3.5.1, TreasureChestReloaded v8.5.1, Citizens v2.0.24-SNAPSHOT (build 1605), Shopkeepers v2.4.1, DiscordSRV v1.16.6, Residence v4.8.4.4, ProtectionLib v0.9.5, CMIEInjector v1.0.1.3, CMI v8.3.8.1, FurnitureLib v2.0.5, DiceFurniture v3.3.0.1
----------------------------------------------------------------------------------------------

More Information: 
(1) Cannot deserialize {Region={Secondary=ctree, 1558, 9, 702, Primary=ctree, 1532, 3, 683}, Name=ch3} to class me.kangarko.boss.api.lib.NamedRegion
CoM9 Location with invalid world 'ctree': ctree, 1532, 3, 683
	 at me.kangarko.boss.final. .coM1.transient(SourceFile:196)
	 at me.kangarko.boss.final. .coM1.deserialize(SourceFile:162)
	 at me.kangarko.boss.final. .I.protected(SourceFile:158)
	 at me.kangarko.boss.final. .I.short(SourceFile:54)
	 at me.kangarko.boss.final. .F.deserialize(SourceFile:154)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at me.kangarko.boss.final. .coM1.deserialize(SourceFile:129)
	 at me.kangarko.boss.final. .I.protected(SourceFile:158)
	 at me.kangarko.boss.final. .I.protected(SourceFile:151)
	 at me.kangarko.boss.api.lib.NamedRegion.deserialize(SourceFile:42)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at me.kangarko.boss.final. .coM1.deserialize(SourceFile:129)
	 at me.kangarko.boss.final. .coM1.deserialize(SourceFile:116)
	 at me.kangarko.boss.final. .bB.short(SourceFile:49)
	 at me.kangarko.boss.final. .W.class(SourceFile:29)
	 at me.kangarko.boss.final. .bB.<init>(SourceFile:32)
	 at me.kangarko.boss.final. .bB.<clinit>(SourceFile:20)
	 at me.kangarko.boss.final. .bc.super(SourceFile:45)
	 at me.kangarko.boss.final. .bc.protected(SourceFile:25)
	 at me.kangarko.boss.api.model.BossRegionType.findRegions(SourceFile:97)
	 at me.kangarko.boss.final. .bI.super(SourceFile:278)
	 at me.kangarko.boss.final. .bI.protected(SourceFile:189)
	 at me.kangarko.boss.final. .bI.transient(SourceFile:161)
	 at me.kangarko.boss.final. .bI.protected(SourceFile:70)
	 at me.kangarko.boss.final. .aO.onSpawn(SourceFile:164)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
	 at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:474)
	 at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:394)
----------------------------------------------------------------------------------------------

`

**Comment by SeanWalk** [comment]
what do you mean?
i need open data.db remove the region manually ?

**Comment by kangarko** [comment]
ZIP the file and upload it here, I will fix it
