### ISSUE TITLE
Boss 2.0.3 cant read settings.yml

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/Boss#266]
When I start the 1.13.2 Spigot server I get an error in the boss error.log. When I run /boss reload I get the same error.
I thought maybe I made a mistake in the settings file so I trashed the whole boss folder, restarted the server so it created a fresh settings file but same error.

------------------------------------[ 10.03.2019 07:21:28 ]-----------------------------------
Boss 2.0.3 encountered a NullPointerException
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_181
Plugins: CoreProtect v2.16.1, dynmap v3.0-SNAPSHOT-170, LuckPerms v4.3.73, WorldEdit v7.0.0-SNAPSHOT;4081-6937cfc, MineZip v1.2.2, PlaceholderAPI v2.9.2, Boss v2.0.3, WorldBorder v1.9.0, WorldGuard v7.0.0-SNAPSHOT;1816-ee7dc27, ProtocolLib v4.4.0, LibsDisguises v9.8.0, GameAPI v1.3.8, MOTD v2.3.2, mcMMO v2.0.0-SNAPSHOT, CreeperHeal v7.0.4, Vault v1.6.11, BottledExp v2.2.5.0, Statz v1.5.3, PerWorldInventory v2.2.1, HeadDatabase v4.8.2, PlotSquared v4.18.12.27-a529518-2116, Dynmap-WorldGuard v1.1-SNAPSHOT, The Multiverse-Core Plugin, DiscordSRV v1.16.6, Shop v1.8.0.1, CoreArena v1.8.10, UltimateTimber v1.0.14, Towny v0.93.0.0, CMI v8.5.1.2, LeaderHeads v3.1.8.3, TownyNameUpdater v2.0, Dynmap-Towny v0.71, TownyFlight v1.2.4, ChatControl v7.13.6
----------------------------------------------------------------------------------------------

More Information: 
Error reloading Boss 2.0.3
NullPointerException (Unknown cause)
	 at me.kangarko.boss.final. .O.protected(SourceFile:23)
	 at me.kangarko.boss.final. .bC.short(SourceFile:50)
	 at me.kangarko.boss.final. .bC.transient(SourceFile:41)
	 at me.kangarko.boss.BossPlugin.super(SourceFile:144)
	 at me.kangarko.boss.final. .lPT5.coM8(SourceFile:544)
	 at me.kangarko.boss.final. .lPT5.cOM3(SourceFile:504)
	 at me.kangarko.boss.command.ReloadCommand.handleSubCommand(SourceFile:20)
	 at me.kangarko.boss.final. .CoM4.handleCommand(SourceFile:172)
	 at me.kangarko.boss.final. .cOm4.onCommand(SourceFile:61)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)

**Comment by kangarko** [comment]
Thanks, fixed.

Use pastebin.com next time
