### ISSUE TITLE
Error clicking in menu prn{} - NullPointerException: Material cannot be null!

### ISSUE THREAD

**Issue by mibby** [kangarko/Boss#272]
Boss v2.2.0
Paper dev 591 (Spigot 1.13.2)

@kangarko Error seems to occur when creating new boss mob configuration and opening the boss menu. Caused by this perhaps in 2.1.3?

> Fix | Solved a menu error when opening New Boss menu on MC 1.8.8

```
[13:56:34] [Server thread/INFO]: player issued server command: /boss menu
[13:56:38] [Server thread/INFO]: player2 issued server command: /boss menu
[13:56:42] [Server thread/INFO]: BOSS // Created default file: Global_Mob1.yml
[13:56:42] [Server thread/INFO]: BOSS // A new Boss was successfully installed: Global_Mob1
[13:56:44] [Timer-2/INFO]: [WorldGuard] Region data changes made in 'spawn' have been background saved
[13:56:47] [Server thread/ERROR]: Error clicking in menu prn{}
java.lang.NullPointerException: Material cannot be null!
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at me.kangarko.boss.final. .bP.protected(SourceFile:385) ~[?:?]
	at me.kangarko.boss.final. .M.protected(SourceFile:37) ~[?:?]
	at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1110) ~[?:?]
	at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1097) ~[?:?]
	at me.kangarko.boss.final. .bF.protected(SourceFile:273) ~[?:?]
	at me.kangarko.boss.final. .bF.short(SourceFile:255) ~[?:?]
	at me.kangarko.boss.final. .bA.protected(SourceFile:157) ~[?:?]
	at me.kangarko.boss.final. .bF.protected(SourceFile:380) ~[?:?]
	at me.kangarko.boss.final. .bG.onMenuClick(SourceFile:74) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-591]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-591]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-591]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-591]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-591]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:56:52] [Server thread/INFO]: BOSS // Created default file: GlobalMob_2.yml
[13:56:52] [Server thread/INFO]: BOSS // A new Boss was successfully installed: GlobalMob_2
[13:57:03] [Server thread/INFO]: player issued server command: /boss menu
[13:57:06] [Server thread/INFO]: player2 issued server command: /boss menu
[13:57:22] [Server thread/ERROR]: Error clicking in menu prn{}
java.lang.NullPointerException: Material cannot be null!
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at me.kangarko.boss.final. .bP.protected(SourceFile:385) ~[?:?]
	at me.kangarko.boss.final. .M.protected(SourceFile:37) ~[?:?]
	at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1110) ~[?:?]
	at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1097) ~[?:?]
	at me.kangarko.boss.final. .bF.protected(SourceFile:273) ~[?:?]
	at me.kangarko.boss.final. .bF.short(SourceFile:255) ~[?:?]
	at me.kangarko.boss.final. .bA.protected(SourceFile:157) ~[?:?]
	at me.kangarko.boss.final. .bF.protected(SourceFile:380) ~[?:?]
	at me.kangarko.boss.final. .bG.onMenuClick(SourceFile:74) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-591]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-591]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-591]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-591]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-591]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-591]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mibby** [comment]
Downgraded to v2.1.2 to try and get it working. Menu opens now but can't open the attributes page.

```
[15:14:33] [Server thread/INFO]: player issued server command: /boss menu
[15:15:29] [Server thread/ERROR]: Error clicking in menu prn{}
java.lang.NullPointerException: Material cannot be null!
	at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at me.kangarko.boss.final. .bO.protected(SourceFile:385) ~[?:?]
	at me.kangarko.boss.final. .M.protected(SourceFile:37) ~[?:?]
	at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1110) ~[?:?]
	at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1097) ~[?:?]
	at me.kangarko.boss.final. .bE.protected(SourceFile:273) ~[?:?]
	at me.kangarko.boss.final. .bE.short(SourceFile:255) ~[?:?]
	at me.kangarko.boss.final. .bz.protected(SourceFile:157) ~[?:?]
	at me.kangarko.boss.final. .bE.protected(SourceFile:380) ~[?:?]
	at me.kangarko.boss.final. .bF.onMenuClick(SourceFile:74) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-597]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-597]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-597]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by SeanWalk** [comment]
Same problem on 2.2.0 with pig_zombie and husk when click attributes 

> [22:32:39 ERROR]: Error clicking in menu prn{}
java.lang.NullPointerException: Material cannot be null!
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_201]
        at me.kangarko.boss.final. .bP.protected(SourceFile:385) ~[?:?]
        at me.kangarko.boss.final. .M.protected(SourceFile:37) ~[?:?]
        at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1110) ~[?:?]
        at me.kangarko.boss.final. .H$aUx.protected(SourceFile:1097) ~[?:?]
        at me.kangarko.boss.final. .bF.protected(SourceFile:273) ~[?:?]
        at me.kangarko.boss.final. .bF.short(SourceFile:255) ~[?:?]
        at me.kangarko.boss.final. .bA.protected(SourceFile:157) ~[?:?]
        at me.kangarko.boss.final. .bF.protected(SourceFile:380) ~[?:?]
        at me.kangarko.boss.final. .bG.onMenuClick(SourceFile:74) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-597]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-597]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-597]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2287) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-597]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1017) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939) ~[patched_1.13.2.jar:git-Paper-597]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-597]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by kangarko** [comment]
Thanks, should be fixed by now. I apology for the inconvenience.
