### ISSUE TITLE
Error and suggestions

### ISSUE THREAD

**Issue by LogGits** [kangarko/Boss#3]
Suggestions:
**(new skill)** Switch - switches the position of the boss and the player.
Enderman - should also set the mobs agro to the player it teleports to.
Config option to disable spawning bosses from mobspawners.

Also i don't know what is causing this error:
```
java.lang.NullPointerException
at me.kangarko.boss.nul. ...\..\\\....cOm6.<init>(SourceFile:11)
at me.kangarko.boss.nul. ...\..\\\....lpt2.nul(SourceFile:147)
at me.kangarko.boss.nul. ...\..\\\....LPT2.nul(SourceFile:21)
at me.kangarko.boss.nul. ...\..\\\....nuL$void.nul(SourceFile:908)
at me.kangarko.boss.nul. ...\..\\\....H.onInvClick(SourceFile:62)
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor708.execute(Unknown Source)
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1934)
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by kangarko** [comment]
I have marked this suggestion thank you.

Error will be fixed :)
