### ISSUE TITLE
Region Spawning issue

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#305]
Hi, so my region spawning seems to be all messed up.. Sometimes it takes like a minute and a half for the boss to spawn inside the region even though my time delay for spawning is set at 10 seconds (I know that's low, but It's just for testing).. Another problem is that when the boss finally spawns, it ignores how many times the boss should be in the said region.. I set the number to 1 (so that boss can spawn in the region only once before he is killed) but the same boss keeps spawning..

This is what it says in the console: 
[01:00:49] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Cigan at world [294, 65, 187] for TIMED
[01:00:49] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.

edit: When the Limit settings was set to 1 in the region, the boss spawned twice and then stopped spawning for another 2 minutes even though I killed the two bosses..

Then I set the limit to unlimited and the boss spawned 4 times and then stopped spawning completely.

Then I set the limit back to 1 again without killing any of the 4 bosses and one more spawned inside the region (giving me 5 bosses..)

edit 2: this is what it says when it manages to spawn the boss:
[01:05:09] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Cigan at world [337, 69, 161] for TIMED
[01:05:09] [Server thread/INFO]: BOSS // [spawning]     [OK] Spawned.

edit 3: jo jinak můžeme se klidně bavit cz/sk :D

**Comment by kangarko** [comment]
Ahoj,

aké boli správy v konzole keď je tam limit 1 ale spawne to 2x a viac?

Keď vypneš limit a prestane spawnovať, aké sú správy?

Skontroluj či nemáš global limit v Limits sekcii v settings.yml na nízku hodnotu a tiež pozri https://github.com/kangarko/Boss/wiki/Common-Issues#my-bosses-are-not-spawning-naturally

**Comment by DogeTennant** [comment]
Tohle mám jako global limits v settings: https://gyazo.com/21ed1a2c4fbbc07f787615b9f13db314 (<- screen)

Když to přestane spawnovat tak to akorát pořád dokola spawmuje tuhle zprávu: 

[00:21:59] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn SurpriceGS at world [-117, 77, -141] for TIMED
[00:21:59] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.

Od včerejška se mi zatím nepodařilo udělat znov aby se boss spawnul 2x v regionu kde je limit nastavenej na jednoho, takže z toho zatím zprávu nemám, ale kdyžtak jí doplním

**Comment by kangarko** [comment]
Správa `Whitelist & Boss is not within any region` znamená že máš zapnutý whitelist na regióny, a Boss nieje v žiadnom vybranom regióne. Túto voľbu môžeš zmeniť v /boss menu -> Bosses -> tvoj Boss -> Spawning -> Regions

Skontrolujem tie limity, ďakujem za upozornenie.

**Comment by kangarko** [comment]
Ok, neviem nájsť problém prosím pošli mi log z konzoly z jedného spawnovacieho cyklu, všetky [spawning] správy. 

Alebo nájdi správu Bosses in region TVOJREGION over limit a pošli mi ju.

**Comment by kangarko** [comment]
A ešte budem potrebovať tvoju Boss/ zložku ako ZIP.

**Comment by DogeTennant** [comment]
Blacklist ve Spawning -> Regions mam vyplý už od začátku, i přes to, to píše tu zprávu. Když blacklist zapnu tak to funguje normálně, ale ovšem se boss spawnuje všude kromě toho regionu.

**Tohle je jeden cyklus kde se vůbec nepodařilo bosse spawnout**
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2595, 63, -5184] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2646, 64, -5170] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2652, 71, -5158] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2662, 29, -5142] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2597, 75, -5146] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2627, 68, -5192] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2611, 63, -5181] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2627, 23, -5155] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2667, 63, -5155] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2638, 66, -5134] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2605, 72, -5135] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2614, 69, -5162] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2619, 74, -5127] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2666, 41, -5181] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2620, 63, -5186] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2640, 18, -5169] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2649, 65, -5121] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2660, 63, -5124] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2632, 69, -5146] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2643, 68, -5143] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2659, 63, -5186] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2610, 69, -5152] for TIMED
[04:25:18] [Server thread/INFO]: BOSS // [spawning]     Bosses in region gareth over limit 1.
[04:25:18] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2599, 67, -5191] for TIMED
[04:25:19] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:19] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2605, 27, -5159] for TIMED
[04:25:19] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:19] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2644, 63, -5190] for TIMED
[04:25:19] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:25:19] [Server thread/INFO]: [Boss 3.2.2] Timed Spawn took 74 ms

**Tohle je druhý cyklus ve kterém se povedlo ho jednou spawnout**
[04:26:03] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2593, 64, -5182] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2644, 63, -5180] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2645, 27, -5159] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2672, 12, -5145] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2601, 69, -5152] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2633, 63, -5185] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2616, 64, -5175] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2635, 22, -5163] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2659, 63, -5157] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2629, 72, -5123] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2596, 74, -5123] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2614, 69, -5159] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     [OK] Spawned.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2622, 81, -5126] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2663, 63, -5183] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2609, 63, -5190] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2631, 63, -5181] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2641, 23, -5125] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2672, 66, -5131] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2634, 69, -5151] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2642, 73, -5148] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2661, 63, -5199] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2613, 71, -5143] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2597, 63, -5187] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2594, 69, -5153] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2644, 63, -5198] for TIMED
[04:26:04] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:04] [Server thread/INFO]: [Boss 3.2.2] Timed Spawn took 203 ms
[04:26:06] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2519, 35, -5153] for CONVERTED
[04:26:06] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:06] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2610, 33, -5228] for CONVERTED
[04:26:06] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:43] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2582, 22, -5101] for CONVERTED
[04:26:43] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.
[04:26:43] [Server thread/INFO]: BOSS // [spawning] Attemt to spawn Gareth at world [-2583, 22, -5102] for CONVERTED
[04:26:43] [Server thread/INFO]: BOSS // [spawning]     Whitelist & Boss is not within any region.

Jediná změna je tam asi to že je tam jedna zpráva "OK Spawned" a  na konci je něco "CONVERTED"

Nevím kde přesně bych měl hledat tu zprávu Bosses in region můjregion over limit, ale jestli v konzoli, tak taková zpráva se tam nikdy neobjevila.

Tohle je moje složka: http://leteckaposta.cz/299549328

Jinak to i nadále ignoruje ten limit nastavený na 1 v tom boss regionu. Boss se třeba 2 cykly nespawne, ale třetí cyklus se spawne a naprosto ignoruje, že do toho regionu ho už jednou spawnul

**Comment by kangarko** [comment]
Ahoj, máš Discord? Môžeme si zavolať. Práve odcestuvávam ale v Nedeľu/Pondelok mi to sedí.

**Comment by DogeTennant** [comment]
Čau, poslal sem ti žádost, na Discord skoro nechodím, ale kvůli tomuhle se tam pokusim být co nejvíc (V neděli asi nebudu mít moc čas max. až večer, ale Pondělí by mělo být úplně v poho.)

**Comment by kangarko** [comment]
Pozriem sa na to, nemohol som prísť skôr prepáč

**Comment by kangarko** [comment]
Ahoj,

dve veci - Boss bude mať čoskoro ďalšiu verziu, mierne som poupravil kód aj tie debug hlášky, keby ešte bol problém tak len repostni debug prosím.

Inak nevidím v súbore bossa Cigán, len Gareth. Platí ten problém aj preňho?

**Comment by DogeTennant** [comment]
Čau, už není problém s tím timed spawningem od toho co jsem zkusil tu verzi 3.2.5, ale když jsem zkusil tu 3.3.0

Tak nemůžu vytvořit nového bosse, napíše mi to do chatu že se objevil error a to konzole to hodí tohle:

------------------------------------[ 03.06.2019 04:53:50 ]-----------------------------------
Boss 3.3.0-BETA encountered a AuX
Running CraftBukkit 1.14.1-R0.1-SNAPSHOT and Java 1.8.0_201
Plugins: Boss v3.3.0-BETA, MMOItems v4.6.2, MMOItemsMana v1.0, Essentials v2.16.1.0, MMOItemsPerWorldDrops v1.1, MMOItemsAnyItemUpdater v1.1
----------------------------------------------------------------------------------------------

More Information: 
Cancel phrases are empty!
AuX Report / Cancel phrases are empty!
	 at org.mineacademy.boss.int. .LPT5.const(SourceFile:73)
	 at org.mineacademy.boss.int. .lPt7.<init>(SourceFile:39)
	 at org.mineacademy.boss.int. .lPt7.<init>(SourceFile:29)
	 at org.mineacademy.boss.int. .lPt7.clone(SourceFile:62)
	 at org.bukkit.conversations.ConversationFactory.buildConversation(ConversationFactory.java:215)
	 at org.mineacademy.boss.int. .CoM7.const(SourceFile:54)
	 at org.mineacademy.boss.int. .Z$LPT9.const(SourceFile:114)
	 at org.mineacademy.boss.int. .U.const(SourceFile:40)
	 at org.mineacademy.boss.int. .U.const(SourceFile:14)
	 at org.mineacademy.boss.int. .PRn.const(SourceFile:220)
	 at org.mineacademy.boss.int. .lPt3.onMenuClick(SourceFile:76)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Ahoj, hned to opravím, ospravedľnujem sa. Ak by sa ešte vyskytol problém so spawnovaním tak prosím pošli ZIP zložku a napíš aký problém je a o akého Bossa sa jedná a pozriem sa na to.
