### ISSUE TITLE
Plugin broke the Walk ability (I know sounds weird)

### ISSUE THREAD

**Issue by Lastphysics** [kangarko/Boss#306]
Hey, really like your plugin, but I just found some kind of bug.

I spawned in couple Bosses that have the ability to throw me away in the sky, killed all of them and now i'm stuck, even in creative mod, I cant move. The only way to move is to jumps at the same time.

Its not very imortant to correct it fast, cause its not a public server, its just on my computer.
But if you could help me with that, it would be great.

(Reload/restart/ and closing and opening again doesnt fix it)

All I have on the console after a new opening is that :
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
        at be.spyproof.spawners.e.a.a(InventoryListener.java:18) ~[Spawners-3.0.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        ... 17 more
>

But could also be another plugin.

If you need a video of what isnt working, i can send you one (couldnt make it work with a Zip somehow :/)

**Comment by kangarko** [comment]
Please update boss to latest version.

That error is from "be.spyproof.spawners.e.a.a" plugin.

**Comment by JustKavis** [comment]
This is still happening this to me, and it's the latest version

**Comment by kangarko** [comment]
@JustKavis then it's SpyProof Spawner's problem, report that to that developer.
