### ISSUE TITLE
health setting error

### ISSUE THREAD

**Issue by LeePC** [kangarko/Boss#394]
[22:04:07] [Server thread/WARN]: [Boss] Plugin Boss v3.4.7 generated an exception whilst handling conversation input
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftSkeleton cannot be cast to org.bukkit.entity.Zombie
at org.mineacademy.boss.double. .cOM3.native(SourceFile:146) ~[Boss-3.4.7.jar:?]
at org.mineacademy.boss.double. .cOM3.const(SourceFile:110) ~[Boss-3.4.7.jar:?]
at org.mineacademy.boss.double. .aG.const(SourceFile:28) ~[Boss-3.4.7.jar:?]
at org.mineacademy.boss.double. .aG.const(SourceFile:18) ~[Boss-3.4.7.jar:?]
at org.mineacademy.boss.double. .O$transient.const(SourceFile:1119) ~[Boss-3.4.7.jar:?]
at org.mineacademy.boss.double. .COM6.conversationAbandoned(SourceFile:103) ~[Boss-3.4.7.jar:?]
at org.bukkit.conversations.Conversation.abandon(Conversation.java:271) ~[mcFG.jar:git-Spigot-79a30d7-acbc348]
at org.mineacademy.boss.double. .COM6$protected.outputNextPrompt(SourceFile:259) ~[Boss-3.4.7.jar:?]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) ~[mcFG.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1118) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1250) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mcFG.jar:git-Spigot-79a30d7-acbc348]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

fix please

**Comment by kangarko** [comment]
Please follow steps including the step three as in https://github.com/kangarko/Boss/issues/341

**Comment by kangarko** [comment]
Closing due to inactivity
