### ISSUE TITLE
Boss plugin is not loaded

### ISSUE THREAD

**Issue by PriestOfTerror** [kangarko/Boss#412]
Hello, I bought your Boss plugin and did not load on the server. Console reports this error:
>[2K [16:42:02] [Server thread/INFO]: [Boss] <0> An error occured: jamF2YS5sYW5nLk5vQ2xhc3NEZWZGb3VuZEVycm9yOiBuZXQvbWRfNS9idW5nZWUvYXBpL2NoYXQvQmFzZUNvbXBvbmVudA==

**Comment by PriestOfTerror** [comment]
And this error: 
>[2K [17:24:03] [Server thread/ERROR]: Error occurred while disabling Boss v3.4.11 (Is it up to date?)
java.lang.IllegalStateException: zip file closed 
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_201] 
at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_201] 
at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_201] 
at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_201] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[server.jar:git-Bukkit-f1f3355] 
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:200) ~[server.jar:git-Bukkit-f1f3355] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[server.jar:git-Bukkit-f1f3355] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[server.jar:git-Bukkit-f1f3355] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201] 
at org.mineacademy.boss.double. .lPT6.throws(SourceFile:764) ~[?:?] 
at org.mineacademy.boss.double. .lPT6.onDisable(SourceFile:627) ~[?:?] 
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Bukkit-f1f3355] 
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:369) [server.jar:git-Bukkit-f1f3355] 
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:436) [server.jar:git-Bukkit-f1f3355] 
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:428) [server.jar:git-Bukkit-f1f3355] 
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:387) [server.jar:git-Bukkit-f1f3355] 
at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:666) [server.jar:git-Bukkit-f1f3355] 
at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:653) [server.jar:git-Bukkit-f1f3355] 
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:799) [server.jar:git-Bukkit-f1f3355] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by kangarko** [comment]
Contacted on SpigotMC.
