### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thetopthailand** [kangarko/Boss#450]
------------------------------------[ 21.09.2562 22:08:43 ]-----------------------------------
Boss 3.4.17 encountered a NullPointerException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_221
Plugins: SupplySign v1.9.8, GroupManager vPre2.14.1.3 FINAL (Phoenix), Boss v3.4.17, NametagEdit v4.3.0, FarmProtect v1.8.0, Lockette v1.8.21, MultiWorld v5.2.7, Unbreakable v3.1, SkinsRestorer v13.5-SNAPSHOT, CustomDrops v3.1.4, VoxelSniper v5.170.0-SNAPSHOT-jnks317-gitfcb8fe1, ViaVersion v2.1.2, AntiCraft v1.1, AntiBot-Ultra v1.3.3, TheRain v1.0.0b-RELEASE, TopLite v1.3.1, Itemizer v3.4, WorldEdit v6.1.3;7a097ca, HologramAPI v1.6.2, TimTheEnchanter v3.0, PvpLevels v1.3, HealthBar v1.8.3, FastCraft v2.0.3, OpenInv v3.1.2, ClearLag v3.0.6, CrackShot v0.98.9, WorldBorder v1.8.4, BotProtect v6.0, MessageAnnouncer v1.10.0, BannerBoard v1.9.10.4, ProtocolLib v4.4.0, NoCheatPlus v3.16.0-RC-sMD5NET-b1134, AdvancedPortals v0.0.41, RandySpawn v1.1, WorldEditCrashFix v2.0, XPFlyX v1.1.0, ChatBubbles v1.5, AntiForceOP v1.0, Vault v1.7.2-b107, ChairStairs v1.1, TimeVote v1.42, AZRank v1.3.b4, HolographicDisplays v2.3.2, Marriage v2.0.19, WorldGuard v6.1, ChestCommands v3.2.0, GangsPlus v2.6.1, CratesPlus v4.5.1, CustomPayloadFixer v1.5, RedstoneClockPreventer v1.3.1, Essentials v2.15.0.1, CommandRegions v2.0.0, KarenProtect v1.3.3, Citizens v2.0.24-SNAPSHOT (build 1605), Shopkeepers v2.2.2, DiscordSRV v1.16.9, CrazyAuctions v1.2.6, EssentialsChat v2.15.0.1, JoinMessagePlus v3.0, NoFlyZone v1.3, ItemLoreStats v6.21, Quests v2.3, EssentialsProtect v2.15.0.1, LeaderHeads v3.1.8.3, ServerSigns v4.5.1, CommandNPC v1.9.1, EssentialsSpawn v2.15.0.1, TitleManager v2.1.3, MyPet v3.3, AuthMe v5.5.0-SNAPSHOT-b2116
----------------------------------------------------------------------------------------------

More Information: 
Error clicking in menu J{}
NullPointerException (Unknown cause)
	 at org.mineacademy.boss.double. .NuL.const(SourceFile:62)
	 at org.mineacademy.boss.double. .NuL.const(SourceFile:50)
	 at org.mineacademy.boss.double. .cOM3.asEgg(SourceFile:295)
	 at org.mineacademy.boss.double. .H.const(SourceFile:29)
	 at org.mineacademy.boss.double. .H.const(SourceFile:16)
	 at org.mineacademy.boss.double. .nUL.const(SourceFile:225)
	 at org.mineacademy.boss.double. .LpT6.const(SourceFile:359)
	 at org.mineacademy.boss.double. .LpT6.private(SourceFile:334)
	 at org.mineacademy.boss.double. .lpt7.const(SourceFile:140)
	 at org.mineacademy.boss.double. .LpT6.const(SourceFile:697)
	 at org.mineacademy.boss.double. .Com5.onMenuClick(SourceFile:74)
	 at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Update to 3.4.19
