### ISSUE TITLE
Spawner error

### ISSUE THREAD

**Issue by thetopthailand** [kangarko/Boss#458]
http://103.131.200.118/error.mp4

[23:59:50 WARN]: Exception in thread "Craft Scheduler Thread - 43"
[23:59:50 WARN]: org.apache.commons.lang.UnhandledException: Plugin Boss v3.4.19 generated an exception while executing task 387
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
        at org.mineacademy.boss.double. .a.const(SourceFile:1625)
        at org.mineacademy.boss.double. .d.super(SourceFile:421)
        at org.mineacademy.boss.double. .d.native(SourceFile:1185)
        at org.mineacademy.boss.double. .az.do(SourceFile:127)
        at org.mineacademy.boss.double. .az.if(SourceFile:70)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by kangarko** [comment]
Please ZIP me your Boss folder in its entirety.

**Comment by thetopthailand** [comment]
http://103.131.200.118/boss.rar

**Comment by kangarko** [comment]
Apology for the delay, I believe to have solved this in Boss 3.5.0, can you please test it again?

**Comment by thetopthailand** [comment]
Ok

**Comment by kangarko** [comment]
I assume it has been fixed? Write below if it was not.
