### ISSUE TITLE
Crashed Plugin

### ISSUE THREAD

**Issue by hyunmin87a** [kangarko/Boss#492]
I don't know why, but there is a collision when driving with the DiscordSRV plugin. This disables the Boss plugin.

[20:53:18 INFO]: java.lang.NullPointerException
[20:53:18 INFO]: at github.scarsz.discordsrv.util.LangUtil$InternalMessage.toString(LangUtil.java:816)
[20:53:18 INFO]: at github.scarsz.discordsrv.api.ApiManager.subscribe(ApiManager.java:63)
[20:53:18 INFO]: at org.mineacademy.boss.lib.fo.model.LpT7$protected.<init>(SourceFile:213)
[20:53:18 INFO]: at org.mineacademy.boss.double. .lPT6.onEnable(SourceFile:313)
[20:53:18 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:53:18 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[20:53:18 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[20:53:18 INFO]: at java.base/java.lang.Thread.run(Thread.java:830)
[20:53:18 INFO]:   _   _                       _
[20:53:18 INFO]:   | | | | ___   ___  _ __  ___| |
[20:53:18 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[20:53:18 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[20:53:18 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[20:53:18 INFO]:                     |_|
[20:53:18 INFO]: !-----------------------------------------------------!
[20:53:18 INFO]: Error loading Boss v3.5.7, plugin is disabled!
[20:53:18 INFO]: Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 13.0.1
[20:53:18 INFO]: !-----------------------------------------------------!
[20:53:18 INFO]: Error: Unable to get the error message, search above.
[20:53:18 INFO]: !-----------------------------------------------------!
[20:53:18 INFO]: [Boss] Disabling Boss v3.5.7

**Comment by hyunmin87a** [comment]
The DiscordSRV plugin was updated and resolved. Thank you.

**Comment by hyunmin87a** [comment]
The DiscordSRV plugin was updated and resolved. Thank you.
