### ISSUE TITLE
Boss Spawning Regions

### ISSUE THREAD

**Issue by virgilio217** [kangarko/Boss#532]
------------------------------------[ 12.04.2020 15:16:52 ]-----------------------------------
Boss 3.7.1 encountered a cd
Running CraftBukkit 1.12-R0.1-SNAPSHOT and Java 1.8.0_241
Plugins: ColorCodes v1.1, Disposal v1.2, PlaceholderAPI v2.10.4, PlugMan v2.1.6, MySQL v1.0.2, UltraCustomizer v1.3.3, Karma v2.0, MoonAnvil v1.0, ReduceSneakDamage v1.3, SkinsRestorer v13.7.5, NoVPN v1.11.6, CraftEnhance v2.3.4, ColoredChat v0.3, Mentions v2.0, ItemRecycler v1.2.4, Furnace_Visuals v1.01, LagMonitor v1.17, ViaVersion v2.2.1, ViaBackwards v2.4.0-SNAPSHOT, ItemEditor v0.1.8, WorldEdit v6.1.9;caf0ad9, Skript v2.2-dev36, SellWands v1.2.8, Trashcan v1.1, ClearLag v3.1.6, ArmorStandEditor v1.11.2-19, UltimateTimber v2.0.4, AutomatedCrafting v1.12/1.14-2.2.1, AntiClicker v1.4.1, MegaSkills v1.5-Stable, BuycraftX v12.0.6, SimpleMachines v1.5, Votifier v1.9, EnchantedFurnace v1.6.10, Multiverse-Core v4.1.0-b775, ProtocolLib v4.5.0, AntiWDL v0.1, NightVision v2.0, NoCheatPlus v3.16.0-RC-sMD5NET-b1134, CharsAPI v0.4.2, MovingDevApi v1.1.1, MVdWPlaceholderAPI v3.0.1, AdvanceParticle v5.2.0, iDisguise v5.8.2, KitPreview v1.3.3-SNAPSHOT, EffectLib v6.1, GrapplingHook v1.5.8.1, SimpleJail v2.1.1, InstantRespawn v1.0.7, AdvancedTPA v2.0.2, ServerListPlus v3.4.8, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, ViaRewind v1.4.5, Masks v1.8.9, MoneyPouch v3.1, HolographicDisplays v2.4.0, WorldGuard v6.2.1;84bc322, NoPlugins v6.9.1, LockettePro v2.9.0, MythicMobs v4.7.2-FREE, EditableSign v7.0.4, AddLight v4.3.2, Whackamole v1.2.4, UltimateRepairing v1.3.4, Essentials v2.17.2.0, SimpleFreeze v3.2.3, HeadDatabase v4.12.1, AutoSell v2.0.10, SafeTrade v1.0.16, CommandSigns v1.6.7, SilkSpawners v5.0.2, Citizens v2.0.25-SNAPSHOT (build 1784), Shopkeepers v2.2.2, AdvancedAchievements v5.13.1, CrazyAuctions v1.2.11-RELEASE, EssentialsChat v2.17.2.0, TimeIsMoney v1.9.6.11, StoneTreasures v2.8.0, Parkour v5.3, DonationsHolograms v1.4.2, UltimateKits v2.5.1, CrazyCrates v1.10-RELEASE, Repuska v1.12, IridiumSkyblock v2.3.4, Boss v3.7.1, ShulkerBoxPlus v1.0.2, BlueShop v2.6, MythicArtifacts v0.1.22, BeastWithdraw v2.7, CombatLogX v9.9.2.1, EssentialsSpawn v2.17.2.0, CrazyEnchantments v1.7.9.4, MyPet v3.8, CoinFlipper v2.43, AuthMe v5.6.0-beta1-b2226
----------------------------------------------------------------------------------------------

More Information: 
Failed WorldEdit 6 legacy hook, see above & report
cd Report / Failed WorldEdit 6 legacy hook, see above & report
	 at org.mineacademy.boss.lib.fo.model.ae.a(SourceFile:2235)
	 at org.mineacademy.boss.lib.fo.model.v.H(SourceFile:1202)
	 at org.mineacademy.boss.double. .ab.a(SourceFile:18)
	 at org.mineacademy.boss.api.BossRegionType.getRegions(SourceFile:78)
	 at org.mineacademy.boss.double. .M$q.a(SourceFile:2091)
	 at org.mineacademy.boss.double. .M$q.a(SourceFile:2039)
	 at org.mineacademy.boss.double. .cy.a(SourceFile:287)
	 at org.mineacademy.boss.double. .M$q.a(SourceFile:2122)
	 at org.mineacademy.boss.double. .cw.a(SourceFile:367)
	 at org.mineacademy.boss.double. .cw.c(SourceFile:342)
	 at org.mineacademy.boss.double. .cE.a(SourceFile:148)
	 at org.mineacademy.boss.double. .cw.a(SourceFile:774)
	 at org.mineacademy.boss.double. .cx.onMenuClick(SourceFile:74)
	 at sun.reflect.GeneratedMethodAccessor469.invoke(Unknown Source)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	 at java.lang.reflect.Method.invoke(Unknown Source)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
----------------------------------------------------------------------------------------------

**Comment by JavaFactoryDev** [comment]
Please follow #432
