### ISSUE TITLE
HELP Could not pass event CreatureSpawnEvent to Boss v3.7.1

### ISSUE THREAD

**Issue by asdzxc852789** [kangarko/Boss#534]
Could not pass event CreatureSpawnEvent to Boss v3.7.1
java.lang.NullPointerException: null
	at org.mineacademy.boss.lib.fo.model.P.a(SourceFile:2097) ~[?:?]
	at org.mineacademy.boss.lib.fo.model.v.e(SourceFile:1169) ~[?:?]
	at org.mineacademy.boss.double. .Z.a(SourceFile:20) ~[?:?]
	at org.mineacademy.boss.api.BossRegionType.findRegions(SourceFile:97) ~[?:?]
	at org.mineacademy.boss.double. .aH.d(SourceFile:309) ~[?:?]
	at org.mineacademy.boss.double. .aH.a(SourceFile:212) ~[?:?]
	at org.mineacademy.boss.double. .aH.b(SourceFile:176) ~[?:?]
	at org.mineacademy.boss.double. .aH.a(SourceFile:70) ~[?:?]
	at org.mineacademy.boss.double. .J.onSpawn(SourceFile:188) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor233.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-105]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:626) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:547) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1214) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1121) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.addEntity(CraftWorld.java:1930) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1937) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1526) ~[patched_1.15.2.jar:git-Paper-105]
	at com.nisovin.shopkeepers.shopobjects.living.SKLivingShopObject.spawn(SKLivingShopObject.java:180) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.spawnShopkeeper(SKShopkeeperRegistry.java:834) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.addShopkeeper(SKShopkeeperRegistry.java:449) ~[?:?]
	at com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry.loadShopkeeper(SKShopkeeperRegistry.java:397) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:368) ~[?:?]
	at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:262) ~[?:?]
	at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:386) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-105]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by JavaFactoryDev** [comment]
Please follow #432
