### ISSUE TITLE
BOSS not compatible with TitleManager v2.2.7

### ISSUE THREAD

**Issue by To0CrAzYy** [kangarko/Boss#563]
Hello, I have the following error on my server where I try to run the BOSS plugin.
It doesn't like the Title manager plugin. Is there a way to fix or patch this?  

[04:07:14 INFO]: [TitleManager] Enabling TitleManager v2.2.7
[04:07:14 ERROR]: Error occurred while enabling TitleManager v2.2.7 (Is it up to date?)
io.puharesource.mc.titlemanager.shaded.kotlin.NotImplementedError: An operation is not implemented.
at io.puharesource.mc.titlemanager.internal.services.animation.ScriptServiceNotFound.loadBuiltinScripts(ScriptServiceNotFound.kt:10) ~[?:?]
at io.puharesource.mc.titlemanager.internal.services.TitleManagerServiceSpigot.start(TitleManagerServiceSpigot.kt:36) ~[?:?]
at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:37) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-350]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-350]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-350]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-350]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-350]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-350]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-350]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-350]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[04:07:14 INFO]: [TitleManager] Disabling TitleManager v2.2.7

**Comment by JavaFactoryDev** [comment]
Hi To0CrAzYy,

thank you for reporting this issue here, but this is a TitleManager issue and has nothing to do with Boss. Please report it in their support.

Regards
Leonhard from MineAcademy
