### ISSUE TITLE
1.16.1 Paper : Error when selecting mob for spawner

### ISSUE THREAD

**Issue by wantduck** [kangarko/Boss#574]
------------------------------------[ 11.08.2020 20:41:44 ]-----------------------------------
Boss 3.8.2 encountered an aL
Running Paper 1.16.1-R0.1-SNAPSHOT and Java 1.8.0_251
Plugins: LuckPerms v5.1.86, WorldEdit v7.1.0;8e55131, EnchantPlus v1.3.4, ClearLag v3.1.6, CrackShot v0.98.9, SetSpawn v3.4, Vault v1.7.3-b131, Lores v1.4.1, ShulkerBoxBackPacks v1.1.4, WorldGuard v7.0.3;5407315, TreasureChest v8.5, Shopkeepers v2.10.0, Boss v3.8.2
----------------------------------------------------------------------------------------------

More Information: 
Expected location (String) but got String: Duckland Unturned! 48 4 50
aL Report / Expected location (String) but got String: Duckland Unturned! 48 4 50
	 at org.mineacademy.boss.double. .ac.a(SourceFile:77)
	 at org.mineacademy.boss.double. .Y.b(SourceFile:335)
	 at org.mineacademy.boss.double. .dX.a(SourceFile:50)
	 at org.mineacademy.boss.double. .dX.g(SourceFile:104)
	 at org.mineacademy.boss.double. .dX.a(SourceFile:91)
	 at org.mineacademy.boss.double. .eb.a(SourceFile:82)
	 at org.mineacademy.boss.double. .bw.onToolClick(SourceFile:77)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor235.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Please ZIP me your Boss folder.
