### ISSUE TITLE
1.16.2: Could not pass event PlayerRespawnEvent to Boss

### ISSUE THREAD

**Issue by ChrisFlyer7** [kangarko/Boss#597]
[15:51:37 ERROR]: Could not pass event PlayerRespawnEvent to Boss v3.8.4
java.lang.IllegalArgumentException: 1.25 is too high
        at org.bukkit.craftbukkit.v1_16_R2.entity.CraftPlayer.validateSpeed(CraftPlayer.java:1701) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.craftbukkit.v1_16_R2.entity.CraftPlayer.setWalkSpeed(CraftPlayer.java:1677) ~[patched_1.16.2.jar:git-Paper-145]
        at org.mineacademy.boss.double. .cX.onDeath(SourceFile:30) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor375.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-145]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-145]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.PlayerList.moveToWorld(PlayerList.java:819) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.PlayerList.moveToWorld(PlayerList.java:716) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2182) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-145]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-145]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by kangarko** [comment]
Thanky will be fixed tonight.
