### ISSUE TITLE
1.16.2: Getting NullpointerException 

### ISSUE THREAD

**Issue by vacoup95** [kangarko/Boss#611]
Hi,

I'm receiving this NullPointerException. I assume this makes it so that the boss doesn't spawn.
I bought this plugin assuming it was good I already have a few questions:

1. Why does the price say €20 and then it ends up costing me €5 extra? Can I have that €5 back?
2. Non-hostile mobs can't be made hostile? 
3. The region tool does not seem to work properly, am I missing something? After I set a secondary it says it said it and then that it removed it again, with a single click.
4. Spawning works but so slow (using WG regions and Boss regions)

```
>.... [18:19:35 ERROR]: Could not pass event BossSpawnEvent to Boss v3.8.6
java.lang.NullPointerException: null
at org.mineacademy.boss.i.aL.b(SourceFile:1885) ~[?:?]
at org.mineacademy.boss.lib.fo.model.c.<init>(SourceFile:65) ~[?:?]
at org.mineacademy.boss.lib.fo.model.c.a(SourceFile:277) ~[?:?]
at org.mineacademy.boss.lib.fo.model.c.b(SourceFile:267) ~[?:?]
at org.mineacademy.boss.lib.boss.util.f.a(SourceFile:95) ~[?:?]
at org.mineacademy.boss.i.K.onBossSpawn(SourceFile:326) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor710.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-178]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-178]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-178]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-178]
at org.mineacademy.boss.i.aL.a(SourceFile:2084) ~[?:?]
at org.mineacademy.boss.i.v.spawn(SourceFile:118) ~[?:?]
at org.mineacademy.boss.lib.boss.util.a.b(SourceFile:196) ~[?:?]
at org.mineacademy.boss.lib.boss.util.a.a(SourceFile:54) ~[?:?]
at org.mineacademy.boss.i.ay.run(SourceFile:77) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-178]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-178]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-178]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-178]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-178]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-178]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-178]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

```

**Comment by kangarko** [comment]
Hi Vacoup95,

Thanks for purchasing Boss. I apology you had a poor first impression. Let me help:

1. The extra 5€ paid is the sales tax in your country. Unfortunately the money does not arrive to me, it is paid to the government. Before completing the purchase, PayPal shows the sales tax in the description column above your contact information, including the sales tax.

2. At this time we are not modifying AI since hooking into NMS is proven to be unstable and caused data loss with pathfinders in the past. In the future we'll use a third party library doing all the work such as Citizens to make passive mobs aggressive. For more information refer to: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai

3. Are you using mouse or a touchpad? If you are on a laptop, it is easy to double-click and thus the newly placed point gets removed. Otherwise simply click once - right/left clicks - to place primary/secondary point - I did a test and it appeared to work correctly. You can also try just having Boss in your plugins to ensure no other plugin is taking over.

4. You have multiple options available to increase spawning. You can decrease the Timed_Spawning.Delay, or increase the chance percentage in the spawning menu in Worlds. Please refer to this article: https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally as well as the questions above/below it as those are relevant.

Thanks for reporting the null pointer exception - while Boss does work out of the box, things like this unavoidable happen due to the size of the plugin. I apology and will include a fix tonight.

**Comment by kangarko** [comment]
Closing in good faith this got resolved and the next version will bring the fix alongside a new addition you asked for, if there is anything I can help you with just comment below.
