### ISSUE TITLE
1.16.3: Cannot measure distance between

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#694]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.

Error output:
[17:06:32 INFO]: [Boss 3.8.17] Command /boss skyblock_adventure 94 174 144 undead_warrior_lvl_8 took 8.65 ms
[17:06:32 WARN]: [Boss] Task #200263 for Boss v3.8.17 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between skyblock_normal_island and skyblock_adventure
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.3.jar:git-Paper-244]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.3.jar:git-Paper-244]
        at org.mineacademy.boss.x.ek$1.run(SourceFile:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-244]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-244]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-244]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

Regards
ludgart

**Comment by kangarko** [comment]
Thanks, will get patched soon!
