### ISSUE TITLE
Minecraft Version: 1.16.3 - issue when translating to spanish

### ISSUE THREAD

**Issue by Drakemlumme** [kangarko/Boss#720]
I'm trying to translate to spanish the skills files, but i'm getting an error and I think everythins its ok

Error:
Error loading skill Throw Player
Error: %error
The skill has not been loaded.
IllegalArgumentException Malformed YAML file Throw Player.yml
	 at org.mineacademy.boss.lib.fo.FileUtil.loadConfigurationStrict(FileUtil.java:254)
	 at org.mineacademy.boss.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:324)
	 at org.mineacademy.boss.api.BossSkillRegistry$SkillConfig.<init>(BossSkillRegistry.java:109)
	 at org.mineacademy.boss.api.BossSkillRegistry$SkillConfig.<init>(BossSkillRegistry.java:101)
	 at org.mineacademy.boss.api.BossSkillRegistry.register(BossSkillRegistry.java:86)
	 at org.mineacademy.boss.api.BossSkillRegistry.registerNative(BossSkillRegistry.java:76)
	 at org.mineacademy.boss.api.BossSkillRegistry.registerDefaults(BossSkillRegistry.java:50)
	 at org.mineacademy.boss.BossPlugin.onReloadablesStart(BossPlugin.java:131)
	 at org.mineacademy.boss.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:304)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
InvalidConfigurationException while parsing a block mapping
 in 'string', line 13, column 1:
    Radius: 5
    ^
expected <block end>, but found '<scalar>'
 in 'string', line 18, column 10:
    - {boss} ha decidido &cpatearte&7!
             ^

File:
Radius: 5
Power: 1.5
Delay: 30 seconds - 1 minute
Message:
- Toma un poco de aire fresco!
- {boss} ha decidido &cpatearte&7!
- Adiós, {player}!

**Comment by kangarko** [comment]
You have a syntax error in your files, use https://yaml-online-parser.appspot.com/ to put your content of that file there.

From what I can tell, put:

- {boss} ha decidido &cpatearte&7!

into "" quotes

- "{boss} ha decidido &cpatearte&7!"

**Comment by Drakemlumme** [comment]
but look at this, this is the original config and dont have quotes:

Radius: 5
Power: 1.2
Delay: 30 seconds - 1 minute
Message:
- Embrace the fresh air in the skies!
- The {boss} has decided to &ckick you&7!
- Good bye, {player}!
_______
and I dont understand this error:
in 'string', line 13, column 1:
Radius: 5
^

**Comment by kangarko** [comment]
You must use quotes when you have & colors there. Use this:

```yaml
Radius: 5
Power: 1.5
Delay: 30 seconds - 1 minute
Message:
- "Toma un poco de aire fresco!"
- "{boss} ha decidido &cpatearte&7!"
- "Adiós, {player}!"
```
