### ISSUE TITLE
1.16.4: LorinthsRpgMobs plugin collision

### ISSUE THREAD

**Issue by ninesik** [kangarko/Boss#731]
------------------------------------[ 22.11.2020 13:01:23 ]-----------------------------------
Boss 3.9.3 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: HackedCore v2.71.4, PluginConstructorAPI v1.0.52, PlaceholderAPI v2.10.9, MMOLib v1.4.1, PlugMan v2.1.7, NumGame v1.0-SNAPSHOT, RecipeControl v3.1, FarmProtect v1.9.0, Oh_the_dungeons_youll_go v10.0, DeluxeTags v1.8.1, MobFarmManager v1.5.9.0, RandomTeleport v2.0-SNAPSHOT (build 71), Geyser-Spigot v1.2.0-SNAPSHOT, LightAPI v3.4.6, LuckPerms v5.2.35, DeathControl v1.0, HackedServer v2.73.0, Votifier v3.0.0-SNAPSHOT, LoneLibs v1.0.6, ProtocolLib v4.6.0-SNAPSHOT-b482, LibsDisguises v10.0.19-SNAPSHOT, Drycell v1.0.7, ServerListPlus v3.5.0-SNAPSHOT, Vault v1.7.3-b131, UltimateBox v0.0.1, TerraformGenerator v1.7.0, EntityTrackerFixer v1.3.3, LastLoginAPI v1.4.3, Parties v2.6.16, HolographicDisplays v2.4.5, UltraCustomizer v1.5.4, Citizens v2.0.27-SNAPSHOT (build 2170), FastAsyncWorldEdit v1.16-437;6ae2275, AdvancedAchievements v6.2.1, TAB v2.8.8, PlotSquared v5.13.8-Premium, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.4+f7ff984, antiRedstoneClock v1.3.0, TradePlus v3.79, NexEngine v2.0.2, WorldGuardExtraFlags v4.1.5-SNAPSHOT, Skript v2.5, MMOItems v6.2.4, SkQuery v4.1.4, Multiverse-Core v4.2.3-SNAPSHOT-b816, Skellett v1.9.11, Shopkeepers v2.12.0, DiscordSRV v1.20.1-SNAPSHOT, Images v2.1.6, SkBee v1.8.3, Multiverse-Inventories v4.2.2-SNAPSHOT-b495, Boss v3.9.3, LorinthsRpgMobs v1.8.8, Lands v4.11.10, QuantumShop v3.10.1, PvPManager v3.13.4, TriggerReactor v3.1.0, CMI v8.7.10.8, ItemsAdder v2.1.19, CMIEInjector v1.0.2.3, Elevator v3.10.7, Insights v5.5.2, CoreProtect v19.3, CMIPaperLib v1.0.0, CustomDrop v1.0
----------------------------------------------------------------------------------------------

More Information: 
Name cannot be null!
FoException Report: Name cannot be null!
	 at org.mineacademy.boss.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.boss.model.BossManager.findBoss(BossManager.java:113)
	 at org.mineacademy.boss.api.BossAPI.getBoss(BossAPI.java:92)
	 at me.lorinth.rpgmobs.handlers.bossSpawn.BossSpawnHandler.spawnBoss(BossSpawnHandler.java:22)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.replaceWithBoss(CreatureModifierManager.java:96)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.updateEntityWithData(CreatureModifierManager.java:71)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.updateEntityWithLevel(CreatureModifierManager.java:62)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.updateEntity(CreatureModifierManager.java:38)
	 at me.lorinth.rpgmobs.Listener.CreatureEventListener.onCreatureSpawn(CreatureEventListener.java:88)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor685.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:673)
	 at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:594)
----------------------------------------------------------------------------------------------

------------------------------------[ 22.11.2020 13:01:25 ]-----------------------------------
Boss 3.9.3 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: HackedCore v2.71.4, PluginConstructorAPI v1.0.52, PlaceholderAPI v2.10.9, MMOLib v1.4.1, PlugMan v2.1.7, NumGame v1.0-SNAPSHOT, RecipeControl v3.1, FarmProtect v1.9.0, Oh_the_dungeons_youll_go v10.0, DeluxeTags v1.8.1, MobFarmManager v1.5.9.0, RandomTeleport v2.0-SNAPSHOT (build 71), Geyser-Spigot v1.2.0-SNAPSHOT, LightAPI v3.4.6, LuckPerms v5.2.35, DeathControl v1.0, HackedServer v2.73.0, Votifier v3.0.0-SNAPSHOT, LoneLibs v1.0.6, ProtocolLib v4.6.0-SNAPSHOT-b482, LibsDisguises v10.0.19-SNAPSHOT, Drycell v1.0.7, ServerListPlus v3.5.0-SNAPSHOT, Vault v1.7.3-b131, UltimateBox v0.0.1, TerraformGenerator v1.7.0, EntityTrackerFixer v1.3.3, LastLoginAPI v1.4.3, Parties v2.6.16, HolographicDisplays v2.4.5, UltraCustomizer v1.5.4, Citizens v2.0.27-SNAPSHOT (build 2170), FastAsyncWorldEdit v1.16-437;6ae2275, AdvancedAchievements v6.2.1, TAB v2.8.8, PlotSquared v5.13.8-Premium, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.4+f7ff984, antiRedstoneClock v1.3.0, TradePlus v3.79, NexEngine v2.0.2, WorldGuardExtraFlags v4.1.5-SNAPSHOT, Skript v2.5, MMOItems v6.2.4, SkQuery v4.1.4, Multiverse-Core v4.2.3-SNAPSHOT-b816, Skellett v1.9.11, Shopkeepers v2.12.0, DiscordSRV v1.20.1-SNAPSHOT, Images v2.1.6, SkBee v1.8.3, Multiverse-Inventories v4.2.2-SNAPSHOT-b495, Boss v3.9.3, LorinthsRpgMobs v1.8.8, Lands v4.11.10, QuantumShop v3.10.1, PvPManager v3.13.4, TriggerReactor v3.1.0, CMI v8.7.10.8, ItemsAdder v2.1.19, CMIEInjector v1.0.2.3, Elevator v3.10.7, Insights v5.5.2, CoreProtect v19.3, CMIPaperLib v1.0.0, CustomDrop v1.0
----------------------------------------------------------------------------------------------

More Information: 
Name cannot be null!
FoException Report: Name cannot be null!
	 at org.mineacademy.boss.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.boss.model.BossManager.findBoss(BossManager.java:113)
	 at org.mineacademy.boss.api.BossAPI.getBoss(BossAPI.java:92)
	 at me.lorinth.rpgmobs.handlers.bossSpawn.BossSpawnHandler.spawnBoss(BossSpawnHandler.java:22)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.replaceWithBoss(CreatureModifierManager.java:96)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.updateEntityWithData(CreatureModifierManager.java:71)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.updateEntityWithLevel(CreatureModifierManager.java:62)
	 at me.lorinth.rpgmobs.Data.CreatureModifierManager.updateEntity(CreatureModifierManager.java:38)
	 at me.lorinth.rpgmobs.Listener.CreatureEventListener.onCreatureSpawn(CreatureEventListener.java:88)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor685.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:673)
	 at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:594)
----------------------------------------------------------------------------------------------

A collision occurs with LorinthsRpgMobs plugin.
I hope this error doesn't appear in the console window.
Can you solve this problem?

https://www.spigotmc.org/resources/lorinthsrpgmobs.53568/

**Comment by kangarko** [comment]
It is a problem in that plugin:

me.lorinth.rpgmobs.handlers.bossSpawn.BossSpawnHandler.spawnBoss(BossSpawnHandler.java:22)

Please contact his author to fix this.
