### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ZappySK** [kangarko/Boss#824]
Always if i want to add drop items, after the boss get killed i get this error:

[14:57:20] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Boss v3.9.10
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R3.NBTTagCompound.a(NBTTagCompound.java:451) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.NBTTagCompound.write(NBTTagCompound.java:92) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:163) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:156) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:112) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1450) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:247) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1376) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.toString(CraftMetaItem.java:1548) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at java.lang.String.valueOf(String.java:2951) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
	at org.bukkit.inventory.ItemStack.toString(ItemStack.java:258) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at java.lang.String.valueOf(String.java:2951) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
	at java.util.AbstractCollection.toString(AbstractCollection.java:473) ~[?:?]
	at java.lang.String.valueOf(String.java:2951) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
	at org.mineacademy.boss.listener.EntityListener.onDeath(EntityListener.java:189) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor992.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:826) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1504) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1426) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1268) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:256) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1085) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2036) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2319) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"2006b9b"]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by kangarko** [comment]
Seems like a Tuinity problem, it is not caused by Boss but by us simply printing the ItemStack that then is serialized on your server which causes issues there instead.
