### ISSUE TITLE
1.16.4: Spawners Breaking

### ISSUE THREAD

**Issue by IAmOrion15** [kangarko/Boss#847]
So I am in the process of setting up an event and I need the spawners. However the issue is that after I restart the server, the spawners break and no longer spawn the bosses. I tried this on paper and spigot and both times, all the spawners placed no longer spawned bosses. I am also using the most current version of the plugin. Do you know how to fix this?

If this is a bug, would you be able to fix it? I REALLY need the spawners to work for my server :).

Oh! And I figure this would be a good time to ask, I know you said you won’t be updating Boss anymore, but will you make the 1.17 mobs available in the GUI?

Thank you for your time and help! :)

EDIT: Alright so after looking at previous issues, it is said that this has been a bug for awhile. So what do I have to do for you to be able to fix it ;) lol.

EDIT 2: Here is the errors that came up. (I tried going to the previous version to see if that'd work but no)

------------------------------------[ 18.03.2021 01:32:02 ]-----------------------------------
Boss 3.9.9 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.8
Plugins: LuckPerms v5.2.35, WorldEdit v7.2.0+a51fa43, MythicMobs v4.11.0-2fb2bf23, NoBreak v1.2.1, NBTAPI v2.6.0, CoreProtect v19.3, Boss v3.9.9
----------------------------------------------------------------------------------------------

More Information: 
Expected location (String) but got String: Romecraft Coliseum 178 22 295
FoException Report: Expected location (String) but got String: Romecraft Coliseum 178 22 295
	 at org.mineacademy.boss.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.boss.lib.fo.SerializeUtil.deserializeLocation(SerializeUtil.java:390)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.onLoadFinish(SimpleSpawnerData.java:50)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.update(SimpleSpawnerData.java:104)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.addSpawner(SimpleSpawnerData.java:91)
	 at org.mineacademy.boss.tool.SpawnerTool.onBlockClick(SpawnerTool.java:82)
	 at org.mineacademy.boss.lib.fo.menu.tool.ToolsListener.onToolClick(ToolsListener.java:80)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor94.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
----------------------------------------------------------------------------------------------

------------------------------------[ 18.03.2021 01:32:02 ]-----------------------------------
Boss 3.9.9 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.8
Plugins: LuckPerms v5.2.35, WorldEdit v7.2.0+a51fa43, MythicMobs v4.11.0-2fb2bf23, NoBreak v1.2.1, NBTAPI v2.6.0, CoreProtect v19.3, Boss v3.9.9
----------------------------------------------------------------------------------------------

More Information: 
Couldn't save spawn-data!
FoException Report: Expected location (String) but got String: Romecraft Coliseum 178 22 295
	 at org.mineacademy.boss.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.boss.lib.fo.SerializeUtil.deserializeLocation(SerializeUtil.java:390)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.onLoadFinish(SimpleSpawnerData.java:50)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.update(SimpleSpawnerData.java:104)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.addSpawner(SimpleSpawnerData.java:91)
	 at org.mineacademy.boss.tool.SpawnerTool.onBlockClick(SpawnerTool.java:82)
	 at org.mineacademy.boss.lib.fo.menu.tool.ToolsListener.onToolClick(ToolsListener.java:80)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor94.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
----------------------------------------------------------------------------------------------

------------------------------------[ 18.03.2021 01:32:07 ]-----------------------------------
Boss 3.9.9 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.8
Plugins: LuckPerms v5.2.35, WorldEdit v7.2.0+a51fa43, MythicMobs v4.11.0-2fb2bf23, NoBreak v1.2.1, NBTAPI v2.6.0, CoreProtect v19.3, Boss v3.9.9
----------------------------------------------------------------------------------------------

More Information: 
Expected location (String) but got String: Romecraft Coliseum 178 22 295
FoException Report: Expected location (String) but got String: Romecraft Coliseum 178 22 295
	 at org.mineacademy.boss.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.boss.lib.fo.SerializeUtil.deserializeLocation(SerializeUtil.java:390)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.onLoadFinish(SimpleSpawnerData.java:50)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.update(SimpleSpawnerData.java:104)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.addSpawner(SimpleSpawnerData.java:91)
	 at org.mineacademy.boss.menu.MenuSpawner$MenuBosses.onPageClick(MenuSpawner.java:184)
	 at org.mineacademy.boss.menu.MenuSpawner$MenuBosses.onPageClick(MenuSpawner.java:153)
	 at org.mineacademy.boss.lib.fo.menu.MenuPagged.onMenuClick(MenuPagged.java:352)
	 at org.mineacademy.boss.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:78)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor92.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------

------------------------------------[ 18.03.2021 01:33:37 ]-----------------------------------
Boss 3.9.9 encountered a FoException
Running Paper 1.16.4-R0.1-SNAPSHOT and Java 11.0.8
Plugins: LuckPerms v5.2.35, WorldEdit v7.2.0+a51fa43, MythicMobs v4.11.0-2fb2bf23, NoBreak v1.2.1, NBTAPI v2.6.0, CoreProtect v19.3, Boss v3.9.9
----------------------------------------------------------------------------------------------

More Information: 
Expected location (String) but got String: Romecraft Coliseum 178 22 295
FoException Report: Expected location (String) but got String: Romecraft Coliseum 178 22 295
	 at org.mineacademy.boss.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.boss.lib.fo.SerializeUtil.deserializeLocation(SerializeUtil.java:390)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.onLoadFinish(SimpleSpawnerData.java:50)
	 at org.mineacademy.boss.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:327)
	 at org.mineacademy.boss.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:260)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.<init>(SimpleSpawnerData.java:36)
	 at org.mineacademy.boss.storage.SimpleSpawnerData.<clinit>(SimpleSpawnerData.java:24)
	 at org.mineacademy.boss.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
We do not support worlds with spaces in their names. Rename "Romecraft Coliseum" to "Romecraft_Coliseum" and it will work.

**Comment by IAmOrion15** [comment]
I don’t know if you’ll see this but I removed the space in the name

**Comment by kangarko** [comment]
You need to recreate the Boss since it still has the old data in it

**Comment by IAmOrion15** [comment]
Thank you for your time again btw! So I managed to get the spawners working after restarts. But the issue now is that I can no longer access the spawners after restart. The bosses also don’t drop the drops I put in their table anymore after restart.

**Comment by kangarko** [comment]
That seems to me like an incompatibility with another plugin or a server. Try running Boss on a test server with no other plugins and a vanilla Paper version.
