### ISSUE TITLE
3.10.0 issue with creating a new boss

### ISSUE THREAD

**Issue by interactii** [kangarko/Boss#857]
While trying to create a new boss with the UI or with the command the following error occurs:

[14:17:44 INFO]: Interactii issued server command: /b new Zembie giant
[14:17:44 INFO]: Boss 3.10.0 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[14:17:44 INFO]: org.mineacademy.boss.lib.fo.exception.FoException: Report: Default 'Zembie.yml' lacks a map at Equipment
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.Valid.checkBoolean(Valid.java:81)
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.settings.YamlConfig.getMap(YamlConfig.java:1304)
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.settings.YamlConfig.getMap(YamlConfig.java:1272)
[14:17:44 INFO]: at org.mineacademy.boss.impl.SimpleSettings.onLoadFinish(SimpleSettings.java:136)
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:335)
[14:17:44 INFO]: at org.mineacademy.boss.impl.SimpleSettings.loadConfig(SimpleSettings.java:100)
[14:17:44 INFO]: at org.mineacademy.boss.impl.SimpleBoss.create(SimpleBoss.java:77)
[14:17:44 INFO]: at org.mineacademy.boss.model.BossManager.createBoss(BossManager.java:84)
[14:17:44 INFO]: at org.mineacademy.boss.command.NewCommand.onCommand(NewCommand.java:41)
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:390)
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:374)
[14:17:44 INFO]: at org.mineacademy.boss.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:390)
[14:17:44 INFO]: !-----------------------------------------------------!
[14:17:44 INFO]: Failed to execute command /b new Zembie giant
[14:17:44 INFO]: !-----------------------------------------------------!

**Comment by kangarko** [comment]
Will fix this in the next release
