### ISSUE TITLE
1.16.5: Error when killing a boss and not displaying a message about his death

### ISSUE THREAD

**Issue by NewJeb** [kangarko/Boss#859]
I am using the latest version of the plugin, everything is configured correctly in the config and I get this error when the player kills the boss. Paper is also the last

>.... [13:16:03 ERROR]: Could not pass event EntityDeathEvent to Boss v3.10.0
java.lang.NullPointerException: null
at net.minecraft.server.v1_16_R3.NBTTagCompound.a(NBTTagCompound.java:457) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.NBTTagCompound.write(NBTTagCompound.java:98) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:166) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:159) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:115) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1476) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:248) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1402) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.toString(CraftMetaItem.java:1574) ~[patched_1.16.5.jar:git-Paper-581]
at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_282]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_282]
at org.bukkit.inventory.ItemStack.toString(ItemStack.java:258) ~[patched_1.16.5.jar:git-Paper-581]
at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_282]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_282]
at java.util.AbstractCollection.toString(AbstractCollection.java:462) ~[?:1.8.0_282]
at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_282]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_282]
at org.mineacademy.boss.listener.EntityListener.onDeath(EntityListener.java:189) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1037.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-581]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-581]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:829) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.EntityLiving.d(EntityLiving.java:1598) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.EntityLiving.die(EntityLiving.java:1520) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1184) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1989) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2396) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-581]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-581]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by kangarko** [comment]
Please use the next Boss release coming up in a few days (or today already) and see if this persists, if yes please repost that error because the error lines have changed already so I cannot trace it back.
