### ISSUE TITLE
Tuinity 1.16.5: Java 16, NashornPlus v1.0.0, Boss disabled

### ISSUE THREAD

**Issue by Gida4** [kangarko/Boss#876]
[07:13:40] [Server thread/INFO]: This server is running Tuinity version git-Tuinity-"901ac35" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
...
[07:13:51] [Server thread/INFO]: [NashornPlus] Loading NashornPlus v1.0.0
...
[07:14:08] [Server thread/INFO]: [NashornPlus] Enabling NashornPlus v1.0.0
...
[07:14:20] [Server thread/WARN]: [Boss] Loaded class org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory from NashornPlus v1.0.0 which is not a depend, softdepend or loadbefore of this plugin.
[07:14:20] [Server thread/INFO]: !-----------------------------------------------------!
[07:14:20] [Server thread/INFO]: ERROR: JavaScript placeholders will not function!
[07:14:20] [Server thread/INFO]:   
[07:14:20] [Server thread/INFO]: Your Java version/distribution lacks the
[07:14:20] [Server thread/INFO]: Nashorn library for JavaScript placeholders.
[07:14:20] [Server thread/INFO]:   
[07:14:20] [Server thread/INFO]: To fix this, install the NashornPlus
[07:14:20] [Server thread/INFO]: plugin from mineacademy.org/nashorn
[07:14:20] [Server thread/INFO]: !-----------------------------------------------------!
[07:14:20] [Server thread/INFO]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[07:14:20] [Server thread/INFO]: at org.mineacademy.boss.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:142)
[07:14:20] [Server thread/INFO]: at org.mineacademy.boss.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:105)
[07:14:20] [Server thread/INFO]: at org.mineacademy.boss.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:354)
[07:14:20] [Server thread/INFO]:     ___                  _
[07:14:20] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[07:14:20] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[07:14:20] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[07:14:20] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[07:14:20] [Server thread/INFO]:              |_|
[07:14:20] [Server thread/INFO]: !-----------------------------------------------------!
[07:14:20] [Server thread/INFO]: Error loading Boss v3.10.4, plugin is disabled!
[07:14:20] [Server thread/INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 16.0.1
[07:14:20] [Server thread/INFO]: !-----------------------------------------------------!
[07:14:20] [Server thread/INFO]: Error: Cannot invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[07:14:20] [Server thread/INFO]: !-----------------------------------------------------!
[07:14:20] [Server thread/INFO]: [Boss] Disabling Boss v3.10.4

**Comment by kangarko** [comment]
To fix this, install the NashornPlus
[07:14:20] [Server thread/INFO]: plugin from mineacademy.org/nashorn

**Comment by Gida4** [comment]
Hey,

not working with NashornPlus v1.1.0:

[06:30:45] [Server thread/INFO]: This server is running Tuinity version
git-Tuinity-"901ac35" (MC: 1.16.5) (Implementing API version
1.16.5-R0.1-SNAPSHOT)
...
[06:30:55] [Server thread/INFO]: [NashornPlus] Loading NashornPlus v1.1.0
...
[06:31:13] [Server thread/INFO]: [NashornPlus] Enabling NashornPlus v1.1.0
...
[06:31:25] [Server thread/WARN]: [Boss] Loaded class
org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory from
NashornPlus v1.1.0 which is not a depend, softdepend or loadbefore of this
plugin.
[06:31:25] [Server thread/INFO]:
!-----------------------------------------------------!
[06:31:25] [Server thread/INFO]: ERROR: JavaScript placeholders will not
function!
[06:31:25] [Server thread/INFO]:
[06:31:25] [Server thread/INFO]: Your Java version/distribution lacks the
[06:31:25] [Server thread/INFO]: Nashorn library for JavaScript
placeholders.
[06:31:25] [Server thread/INFO]:
[06:31:25] [Server thread/INFO]: To fix this, install the NashornPlus
[06:31:25] [Server thread/INFO]: plugin from mineacademy.org/nashorn
[06:31:25] [Server thread/INFO]:
!-----------------------------------------------------!
[06:31:25] [Server thread/INFO]: java.lang.NullPointerException: Cannot
invoke "org.bukkit.command.CommandSender.getName()" because "sender" is null
[06:31:25] [Server thread/INFO]: at
org.mineacademy.boss.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:142)
[06:31:25] [Server thread/INFO]: at
org.mineacademy.boss.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:105)
[06:31:25] [Server thread/INFO]: at
org.mineacademy.boss.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:354)
[06:31:25] [Server thread/INFO]:     ___                  _
[06:31:25] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[06:31:25] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[06:31:25] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[06:31:25] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[06:31:25] [Server thread/INFO]:              |_|
[06:31:25] [Server thread/INFO]:
!-----------------------------------------------------!
[06:31:25] [Server thread/INFO]: Error loading Boss v3.10.4, plugin is
disabled!
[06:31:25] [Server thread/INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3)
& Java 16.0.1
[06:31:25] [Server thread/INFO]:
!-----------------------------------------------------!
[06:31:25] [Server thread/INFO]: Error: Cannot invoke
"org.bukkit.command.CommandSender.getName()" because "sender" is null
[06:31:25] [Server thread/INFO]:
!-----------------------------------------------------!
[06:31:25] [Server thread/INFO]: [Boss] Disabling Boss v3.10.4


Matej Pacan ***@***.***> ezt írta (időpont: 2021. jún. 11.,
P, 20:12):

**Comment by kangarko** [comment]
[06:31:25] [Server thread/INFO]:
[06:31:25] [Server thread/INFO]: Your Java version/distribution lacks the
[06:31:25] [Server thread/INFO]: Nashorn library for JavaScript
placeholders.
[06:31:25] [Server thread/INFO]:
[06:31:25] [Server thread/INFO]: To fix this, install the NashornPlus
[06:31:25] [Server thread/INFO]: plugin from mineacademy.org/nashorn
[06:31:25] [Server thread/INFO]:
!------------------------------------------------

**Comment by Gida4** [comment]
06:30:45] [Server thread/INFO]: This server is running Tuinity version
git-Tuinity-"901ac35" (MC: 1.16.5) (Implementing API version
1.16.5-R0.1-SNAPSHOT)
...
[06:30:55] [Server thread/INFO]: [NashornPlus] Loading NashornPlus v1.1.0
...
[06:31:13] [Server thread/INFO]: [NashornPlus] Enabling NashornPlus v1.1.0

Matej Pacan ***@***.***> ezt írta (időpont: 2021. jún. 17.,
Cs, 14:31):

**Comment by kangarko** [comment]
Try the next version please. If still won't work please post  your full startup log uploaded to pastebin.com
