### ISSUE TITLE
Minecraft Version: 1.17 Bucket error with unknown problem

### ISSUE THREAD

**Issue by ninesik** [kangarko/Boss#888]
[00:09:08 ERROR]: Could not pass event CreatureSpawnEvent to Boss v3.10.5
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.MinecraftKey.getNamespace()" because "minecraft" is null
        at org.bukkit.craftbukkit.v1_17_R1.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:518) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getBiome(CraftWorld.java:1121) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getBiome(CraftWorld.java:1116) ~[patched_1.17.jar:git-Purpur-1236]
        at org.mineacademy.boss.util.BossConditionedSpawnUtil.canTransform(BossConditionedSpawnUtil.java:271) ~[?:?]
        at org.mineacademy.boss.util.BossConditionedSpawnUtil.spawnConditioned(BossConditionedSpawnUtil.java:209) ~[?:?]
        at org.mineacademy.boss.util.BossConditionedSpawnUtil.convert(BossConditionedSpawnUtil.java:90) ~[?:?]
        at org.mineacademy.boss.listener.SpawningListener.onSpawn(SpawningListener.java:192) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor545.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Purpur-1236]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:718) ~[patched_1.17.jar:git-Purpur-1236]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:638) ~[patched_1.17.jar:git-Purpur-1236]
        at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1489) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1401) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addAllEntities$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addAllEntities(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:299) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:216) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:196) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1034) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:932) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:789) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.jar:git-Purpur-1236]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.jar:git-Purpur-1236]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1478) ~[patched_1.17.jar:git-Purpur-1236]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1262) ~[patched_1.17.jar:git-Purpur-1236]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1236]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by kangarko** [comment]
I cannot reproduce this under Paper 1.17.1 the latest build, do not use third party forks if you are experiencing issues.
