### ISSUE TITLE
Issue with boss regions.

### ISSUE THREAD

**Issue by jmancox330** [kangarko/Boss#907]
Version: 1.17.1

Issue: I can only add one boss region to my server. After I add a boss region, I must restart the server before creating another one, or else the current boss region will be replaced with the new one. 

Error log: 
------------------------------------[ 10.10.2021 18:21:38 ]-----------------------------------
Boss 3.11.0 encountered a FoException
Running Paper 1.17.1-R0.1-SNAPSHOT and Java 16.0.1
Plugins: SimpleNoCropTrample v1.0, PlaceholderAPI v2.10.9, PvPLevels v2.2.4, ViaVersion v4.0.1, BuycraftX v12.0.7, EliteLootbox v2.2.4, ViaBackwards v4.0.1, ProtocolLib v4.7.0, ViaRewind v2.0.1, LuckPerms v5.3.47, AnimatedScoreboard v0.2.4, ChatInjector v1.0.2, Vault v1.7.3-b131, Multiverse-Core v4.3.0-b846, WorldEdit v7.2.6+4b2d1e7, AsyncWorldEdit v3.9.1, Essentials v2.19.0, EssentialsChat v2.19.0, Boss v3.11.0, WorldGuard v7.0.5+3827266, MythicLib v1.1.3, MMOCore v1.8.0, MMOItems v6.6.1, Breaker v1.4.2
----------------------------------------------------------------------------------------------

More Information: 
Value 'VisualizedRegion{name=OpeningToCopper,location=world [-246, 107, -150] - world [-282, 161, -129]}' is already in the list!
FoException Report: Value 'VisualizedRegion{name=OpeningToCopper,location=world [-246, 107, -150] - world [-282, 161, -129]}' is already in the list!
	 at Boss-3.11.0.jar//org.mineacademy.boss.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at Boss-3.11.0.jar//org.mineacademy.boss.lib.fo.collection.StrictList.add(StrictList.java:131)
	 at Boss-3.11.0.jar//org.mineacademy.boss.storage.SimpleRegionData.addRegion(SimpleRegionData.java:105)
	 at Boss-3.11.0.jar//org.mineacademy.boss.command.RegionCommand.onCommand(RegionCommand.java:108)
	 at Boss-3.11.0.jar//org.mineacademy.boss.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:396)
	 at Boss-3.11.0.jar//org.mineacademy.boss.lib.fo.command.SimpleCommandGroup$MainCommand.onCommand(SimpleCommandGroup.java:399)
	 at Boss-3.11.0.jar//org.mineacademy.boss.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:396)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:852)
----------------------------------------------------------------------------------------------

**Comment by jmancox330** [comment]
No problem, thanks for fixing it!
