### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by KlasterStormInc** [kangarko/Boss#96]
Hello, I have installed the last version and I have this error.
Boss 1.6.10 encountered a cOm9! Please check your error.log and report this issue with the information in that file. 
> [19:59:33 WARN]: [Boss] Task #6498 for Boss v1.6.10 generated an exception 
me.kangarko.boss.final. .cOm9: Report / Cannot remove '7e8432dc-5878-4277-9f12-0e8651e6e2b9' as it is not in the list! 
at me.kangarko.boss.final. .com2.protected(SourceFile:30) ~[Boss-1.6.10.jar:?] 
at me.kangarko.boss.final. .B.protected(SourceFile:58) ~[Boss-1.6.10.jar:?] 
at me.kangarko.boss.final. .aE$aux.run(SourceFile:260) ~[Boss-1.6.10.jar:?] 
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24] 
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by kangarko** [comment]
Hello KlasterStormInc,

I apology for a late reply. Thank you for your report, the next version will include a fix.
