### ISSUE TITLE
Spigot 1.18.1-R0.1-SNAPSHOT: Boss 4.1.8 encountered an InvalidConfigurationException!

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/Boss#981]
Plugins spit out many errors during server booting. Freshly installed so the config files are all default.

Below one example of the Boss plugin error log. Seems that both Boss and Corearena generate these errors. Confiscate and ChatControl Red are ok.

`------------------------------------[ 14.01.2022 11:24:44 ]-----------------------------------
Boss 4.1.8 encountered an InvalidConfigurationException
Running CraftBukkit 1.18.1-R0.1-SNAPSHOT and Java 17.0.1
Plugins: SuperElytra v2.3, LuckPerms v5.3.86, BlueMap v1.7.2, MineZip v1.2.2, PlaceholderAPI v2.11.1, ProtocolLib v4.8.0-SNAPSHOT-b539, SteamBath v1.6, AdvancedNMotd v9.2.0, Vault v1.7.3-b131, WorldEdit v7.2.9-SNAPSHOT+6053-512a07e, HeadDatabase v4.15.1, WorldGuard v7.0.7-SNAPSHOT+2165-81750e1, Multiverse-Core v4.3.2-SNAPSHOT-b867, Citizens v2.0.29-SNAPSHOT (build 2419), mcMMO v2.1.208, CoreProtect v20.4, Blacksmith v1.12, Towny v0.97.5.9, WorldBorder v1.18, TownyHistories v0.0.9, Sentinel v2.4.0-SNAPSHOT (build 446), DiscordSRV v1.24.1-SNAPSHOT, Shop v1.8.3.4, TownyCamps v0.0.16, Confiscate v3.0.9, ChatControlRed v10.9.3, MobHunting v8.0.6, UltimateTimber v2.3.0, CMILib v1.1.0.8, Jobs v5.0.1.1, CMI v9.1.0.6, TabList v5.6.1, CMIEInjector v1.0.2.3, SelectionVisualizer v3.1.0.0, Boss v4.1.8, CoreArena v3.1.0
----------------------------------------------------------------------------------------------

More Information: 
Failed to save messages_en.yml
InvalidConfigurationException could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.configuration.MemorySection
 in 'string', line 15, column 11:
    Commands: !!org.bukkit.configuration.Memor ... 
              ^

	 at org.mineacademy.boss.lib.settings.SimpleYaml.loadFromString(SimpleYaml.java:105)
	 at org.mineacademy.boss.lib.settings.YamlComments.writeComments(YamlComments.java:81)
	 at org.mineacademy.boss.lib.settings.ConfigInstance.save0(YamlConfig.java:2044)
	 at org.mineacademy.boss.lib.settings.ConfigInstance.save(YamlConfig.java:2025)
	 at org.mineacademy.boss.lib.settings.YamlConfig.saveWithoutSerializing(YamlConfig.java:469)
	 at org.mineacademy.boss.lib.settings.YamlConfig.save(YamlConfig.java:465)
	 at org.mineacademy.boss.lib.settings.YamlConfig.saveIfNecessary0(YamlConfig.java:367)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:356)
	 at org.mineacademy.boss.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:272)
	 at org.mineacademy.boss.lib.settings.Lang.<init>(Lang.java:33)
	 at org.mineacademy.boss.lib.settings.Lang.init(Lang.java:75)
	 at org.mineacademy.boss.lib.settings.Lang.init(Lang.java:64)
	 at org.mineacademy.boss.lib.settings.Lang.checkInit(Lang.java:279)
	 at org.mineacademy.boss.lib.settings.Lang.of(Lang.java:241)
	 at org.mineacademy.boss.command.BiomeCommand.<init>(BiomeCommand.java:24)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	 at org.mineacademy.boss.lib.ReflectionUtil.instantiate(ReflectionUtil.java:483)
	 at org.mineacademy.boss.command.BossCommandGroup.registerSubcommands(BossCommandGroup.java:36)
	 at org.mineacademy.boss.lib.command.SimpleCommandGroup.register(SimpleCommandGroup.java:108)
	 at org.mineacademy.boss.lib.plugin.Reloadables.registerCommands(Reloadables.java:85)
	 at org.mineacademy.boss.lib.plugin.SimplePlugin.registerCommands(SimplePlugin.java:869)
	 at org.mineacademy.boss.lib.plugin.AutoRegisterScanner.scan(AutoRegisterScanner.java:212)
	 at org.mineacademy.boss.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:107)
	 at org.mineacademy.boss.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:288)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526)
	 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440)`

**Comment by gerardvanschip** [comment]
Just a quick follow up. Even with all plugins disabled do I get errors.

**Comment by gerardvanschip** [comment]
Interesting. Just did a quick test with paper and both Boss and CoreArena work fine on paper. Switched back and forth a few times and can confirm the latest spigot wont run Boss and CoreArena.

**Comment by kangarko** [comment]
Seems like some issues with the most recent Paper. Please stay on the older build for now as I am investigating a solution.
